### ISSUE TITLE
import error trying master.

### ISSUE THREAD

**Issue by kodispot** [Razzeee/script.trakt#109]
Hi! I have this error trying the master branch:

                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named six
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/script.trakt/script.py", line 2, in <module>
                                                import utilities as utils
                                              File "/storage/.xbmc/addons/script.trakt/utilities.py", line 11, in <module>
                                                from dateutil.tz import tzutc, tzlocal
                                              File "/storage/.xbmc/addons/script.trakt/dateutil/tz.py", line 16, in <module>
                                                from six import string_types, PY3
                                            ImportError: No module named six
                                            -->End of Python script error report<--

**Comment by Razzeee** [comment]
@kodispot 
don't copy it, install it by zip so that it will add all the needed dependencies

**Comment by kodispot** [comment]
I've got an structure error installing it from zip.

**Comment by Razzeee** [comment]
Then read this https://github.com/Razzeee/script.trakt#installation

**Comment by kodispot** [comment]
SOLVED! thx!
