### ISSUE TITLE
Script error on startup

### ISSUE THREAD

**Issue by brimur** [Razzeee/script.trakt#111]
I'm getting the error below on startup. Using the latest Master which seems to be the same as Dev today.

````
 EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.trakt/default.py", line 15, in <module>
                                                traktService().run()
                                              File "/storage/.kodi/addons/script.trakt/service.py", line 104, in run
                                                globals.traktapi = traktAPI()
                                              File "/storage/.kodi/addons/script.trakt/traktapi.py", line 35, in __init__
                                                self.getToken()
                                              File "/storage/.kodi/addons/script.trakt/traktapi.py", line 60, in getToken
                                                auth = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "/storage/.kodi/addons/script.trakt/trakt/interfaces/auth.py", line 10, in login
                                                'password': password
                                              File "/storage/.kodi/addons/script.trakt/trakt/core/http.py", line 89, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/storage/.kodi/addons/script.trakt/trakt/core/http.py", line 66, in request
                                                response = self.session.send(prepared, timeout=timeout)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 569, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 407, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
                                            -->End of Python script error report<--

````

**Comment by Razzeee** [comment]
Might want to add a startup delay in the addon settings.  Or if your using openelec try the openelec settings there should be an option that waits for the network to connect.

**Comment by brimur** [comment]
Sorry, my bad, something wiped my DNS servers so I could access the box locally but the box couldn't access web sites.
