### ISSUE TITLE
Fresh install from Github script error

### ISSUE THREAD

**Issue by fightnight** [Razzeee/script.trakt#123]
Hi, i've just installed from this github main tree and I'm getting this:

09:22:23 T:3272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named six
                                            Traceback (most recent call last):
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.trakt\default.py", line 5, in <module>
                                                import kodilogging
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.trakt\kodilogging.py", line 19, in <module>
                                                from utilities import getSettingAsBool
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.trakt\utilities.py", line 11, in <module>
                                                from dateutil.tz import tzutc, tzlocal
                                              File "C:\Users\User\AppData\Roaming\Kodi\addons\script.trakt\dateutil\tz.py", line 16, in <module>
                                                from six import string_types, PY3
                                            ImportError: No module named six
                                            -->End of Python script error report<--

**Comment by fightnight** [comment]
Figured what's wrong. Not installing as zip doesn't import the required modules.
