### ISSUE TITLE
Crash when syncing

### ISSUE THREAD

**Issue by blinkseb** [Razzeee/script.trakt#15]
Hi there,

Since today, I observe a crash with latest trakt plugin (dev branch) when syncing occur:

```
Traceback (most recent call last):
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/threadi
ng.py", line 551, in __bootstrap_inner
                                              File "/storage/.kodi/addons/script.trakt/service.py", line 273, in run
                                                sync.sync()
                                              File "/storage/.kodi/addons/script.trakt/sync.py", line 635, in sync
                                                self.__syncMovies()
                                              File "/storage/.kodi/addons/script.trakt/sync.py", line 601, in __syncMovies
                                                self.__traktUpdateMovies(traktMoviesToUpdate)
                                              File "/storage/.kodi/addons/script.trakt/sync.py", line 505, in __traktUpdateMovies
                                                titles = ", ".join(["%s (%s)" % (m['title'], m['ids']['imdb']) for m in movies])
                                            KeyError: 'imdb'
```

Indeed, the `ids` dictionnary is empty. Since it's only use in the debug string, it should be fairly easu to fix.

Thanks for your hard work!

**Comment by Razzeee** [comment]
@blinkseb 
please try again and let me know if it works.

**Comment by blinkseb** [comment]
Almost, new error now, this time with the `tmdb` id:

```
                                            Traceback (most recent call last):
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.0/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
                                              File "/storage/.kodi/addons/script.trakt/service.py", line 273, in run
                                                sync.sync()
                                              File "/storage/.kodi/addons/script.trakt/sync.py", line 609, in sync
                                                self.__syncMovies()
                                              File "/storage/.kodi/addons/script.trakt/sync.py", line 575, in __syncMovies
                                                self.__traktUpdateMovies(traktMoviesToUpdate)
                                              File "/storage/.kodi/addons/script.trakt/sync.py", line 479, in __traktUpdateMovies
                                                titles = ", ".join(["%s (%s)" % (m['title'], m['ids']['tmdb']) for m in movies])
                                            KeyError: 'tmdb'
```

Thanks!

**Comment by Razzeee** [comment]
@blinkseb 
seems like you got a movie there that has no imdb id in kodi. 
Should handle it better with the latest commit, but there might be atleast one error following

**Comment by Jobespierre** [comment]
Hi Razze, I just grabbed the latest from github and getting similar error as well

Im on helix (14.0 Git:2014-12-23-ad747d9-dirty). Platform: OS X x86 64-bit Kodi x64 build

Code:
07:51:44 T:4573978624  NOTICE: [trakt] [Movies Sync] Getting movie collection from trakt.tv
07:51:50 T:4573978624   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "/Users/Shared/jenkins/workspace/OSX-64/tools/depends/xbmc-depends/macosx10.8_x86_64-target/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                                              File "/Users/jobvanderheijden/Library/Application Support/Kodi/addons/script.trakt-dev/service.py", line 273, in run
                                                sync.sync()
                                              File "/Users/jobvanderheijden/Library/Application Support/Kodi/addons/script.trakt-dev/sync.py", line 609, in sync
                                              File "/Users/jobvanderheijden/Library/Application Support/Kodi/addons/script.trakt-dev/sync.py", line 575, in __syncMovies
                                              File "/Users/jobvanderheijden/Library/Application Support/Kodi/addons/script.trakt-dev/sync.py", line 479, in __traktUpdateMovies
                                                Debug("[Movies Sync] trakt.tv movie playcount is up to date")
                                            KeyError: 'tmdb'

**Comment by Razzeee** [comment]
@Jobespierre 
Should probably retry again with the latest, the one above don't really seems like its that new.

**Comment by Jobespierre** [comment]
Yup, this is now working correct.
