### ISSUE TITLE
Trakt not allowing to give vote and not syncing all the data after the show ended

### ISSUE THREAD

**Issue by hpio** [razzeee/script.trakt#188]
So I was watching a show yesterday through XBMC and could see Trakt updating the progress on trakt.tv . Right after the show ended Trakt was suppose to let me vote but instead i got an error script:error . Also it didn't mark the show as watched in my profile.

Let me know if you need more information

Here's the error:

```
22:21:05 T:140420645369600  NOTICE: [trakt] [traktAPI] watching(url: https://api.trakt.tv/show/watching/b6135e0f7510a44021fac8c03c36c81a17be35d9, data: {'episode': 5, 'title': u'The Americans (2013)', 'season': 1, 'tvdb_id': u'261690', 'episode_tvdb_id': u'4429002', 'year': 2013, 'duration': 40.0, 'progress': 77.0})
22:21:05 T:140420645369600  NOTICE: [trakt] [traktAPI] traktRequest(): Request data: '{"episode": 5, "title": "The Americans (2013)", "season": 1, "tvdb_id": "261690", "episode_tvdb_id": "4429002", "year": 2013, "duration": 40.0, "progress": 77.0}'.
22:21:05 T:140420645369600  NOTICE: [trakt] [traktAPI] traktRequest(): Starting retry loop, maximum 5 retries.
22:21:05 T:140420645369600  NOTICE: [trakt] [traktAPI] traktRequest(): (0) Request URL 'https://api.trakt.tv/show/watching/b6135e0f7510a44021fac8c03c36c81a17be35d9'
22:21:05 T:140420645369600  NOTICE: [trakt] [traktAPI] __getData(): urllib2.Request(https://api.trakt.tv/show/watching/b6135e0f7510a44021fac8c03c36c81a17be35d9)
22:21:05 T:140420645369600  NOTICE: [trakt] [traktAPI] __getData(): urllib2.urlopen()
22:21:12 T:140420645369600  NOTICE: [trakt] [traktAPI] __getData(): response.read()
22:21:12 T:140420645369600  NOTICE: [trakt] [traktAPI] __getData(): Response Code: 200
22:21:12 T:140420645369600  NOTICE: [trakt] [traktAPI] __getData(): Response Time: 7539.98 ms
22:21:12 T:140420645369600  NOTICE: [trakt] [traktAPI] __getData(): Response Headers: {'x-powered-by': 'PHP/5.5.11-1~dotdeb.1', 'transfer-encoding': 'chunked', 'set-cookie': '__cfduid=da65786e8683b735e8b828adc8252f8b01415139665609; expires=Mon, 23-Dec-2019 23:50:00 GMT; path=/; domain=.trakt.tv; HttpOnly', 'expires': 'Wed, 05 Nov 2014 22:21:12 GMT', 'vary': 'Accept-Encoding', 'server': 'cloudflare-nginx', 'connection': 'close', 'cache-control': 'public, max-age=86400', 'date': 'Tue, 04 Nov 2014 22:21:12 GMT', 'cf-ray': '184433de03b50ccb-LHR', 'content-type': 'application/json'}
22:21:12 T:140420645369600  NOTICE: [trakt] [traktAPI] traktRequest(): (0) JSON response: '{u'status': u'success', u'episode': {u'number': 5, u'title': u'COMINT'}, u'show': {u'tvdb_id': 261690, u'year': 2013, u'imdb_id': u'tt2149175', u'title': u'The Americans (2013)'}, u'season': 1, u'twitter': False, u'tumblr': False, u'facebook': False, u'path': False, u'message': u'watching The Americans (2013) 1x05'}'
22:21:12 T:140420645369600  NOTICE: [trakt] [traktAPI] traktRequest(): JSON request was successful.
22:21:12 T:140420645369600  NOTICE: [trakt] [Scrobbler] Watch response: {u'status': u'success', u'episode': {u'number': 5, u'title': u'COMINT'}, u'show': {u'tvdb_id': 261690, u'year': 2013, u'imdb_id': u'tt2149175', u'title': u'The Americans (2013)'}, u'season': 1, u'twitter': False, u'tumblr': False, u'facebook': False, u'path': False, u'message': u'watching The Americans (2013) 1x05'}
22:30:15 T:140420714637056 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
22:30:16 T:140420725389056 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
22:30:16 T:140420746954496  NOTICE: CDVDPlayer::OnExit()
22:30:16 T:140420746954496  NOTICE: DVDPlayer: eof, waiting for queues to empty
22:30:16 T:140420746954496  NOTICE: DVDPlayer: closing audio stream
22:30:16 T:140420746954496  NOTICE: Closing audio stream
22:30:16 T:140420746954496  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
22:30:16 T:140420746954496  NOTICE: Waiting for audio thread to exit
22:30:16 T:140420714637056  NOTICE: thread end: CDVDPlayerAudio::OnExit()
22:30:16 T:140420746954496  NOTICE: Closing audio device
22:30:16 T:140420746954496  NOTICE: Deleting audio codec
22:30:16 T:140420746954496  NOTICE: DVDPlayer: closing video stream
22:30:16 T:140420746954496  NOTICE: Closing video stream
22:30:16 T:140420746954496  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
22:30:16 T:140420746954496  NOTICE: waiting for video thread to exit
22:30:16 T:140420725389056   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
22:30:16 T:140420725389056  NOTICE: thread end: video_thread
22:30:16 T:140420746954496  NOTICE: deleting video codec
22:30:16 T:140420746954496  NOTICE: DVDPlayer: closing subtitle stream
22:30:16 T:140420746954496  NOTICE: Closing subtitle stream
22:30:16 T:140420746954496  NOTICE: CDVDPlayer::OnExit() deleting demuxer
22:30:16 T:140420746954496  NOTICE: CDVDPlayer::OnExit() deleting input stream
22:30:16 T:140420746954496  NOTICE: Thread BackgroundLoader start, auto delete: false
22:30:16 T:140421539821312  NOTICE: [trakt] [traktPlayer] onPlayBackEnded() - 0
22:30:16 T:140421539821312  NOTICE: [trakt] Queuing for dispatch: {'action': 'ended'}
22:30:16 T:140422580152256  NOTICE: CDVDPlayer::CloseFile()
22:30:16 T:140422580152256  NOTICE: DVDPlayer: waiting for threads to exit
22:30:16 T:140422580152256  NOTICE: DVDPlayer: finished waiting
22:30:16 T:140422580152256  NOTICE: CDVDPlayer::CloseFile()
22:30:16 T:140422580152256  NOTICE: DVDPlayer: waiting for threads to exit
22:30:16 T:140422580152256  NOTICE: DVDPlayer: finished waiting
22:30:16 T:140420746954496  NOTICE: Thread JobWorker start, auto delete: true
22:30:16 T:140421539821312  NOTICE: [trakt] Queued dispatch: {u'action': u'ended'}
22:30:16 T:140421539821312  NOTICE: [trakt] Dispatch: {u'action': u'ended'}
22:30:16 T:140421539821312  NOTICE: [trakt] [Scrobbler] playbackEnded()
22:30:16 T:140421539821312  NOTICE: [trakt] [Rating] Rating Check called for 'episode'
22:30:16 T:140421539821312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: getAccountSettings() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "/home/piotr/.xbmc/addons/script.trakt/default.py", line 13, in <module>
                                                traktService().run()
                                              File "/home/piotr/.xbmc/addons/script.trakt/service.py", line 142, in run
                                                self._dispatch(data)
                                              File "/home/piotr/.xbmc/addons/script.trakt/service.py", line 47, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/home/piotr/.xbmc/addons/script.trakt/scrobbler.py", line 212, in playbackEnded
                                                ratingCheck(self.curVideo['type'], self.traktSummaryInfo, self.watchedTime, self.videoDuration, self.playlistLength)
                                              File "/home/piotr/.xbmc/addons/script.trakt/rating.py", line 25, in ratingCheck
                                                rateMedia(media_type, summary_info)
                                              File "/home/piotr/.xbmc/addons/script.trakt/rating.py", line 45, in rateMedia
                                                globals.traktapi.getAccountSettings()
                                            TypeError: getAccountSettings() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--
22:30:16 T:140422178580224  NOTICE: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms
22:30:52 T:140420746954496  NOTICE: Thread JobWorker start, auto delete: true
22:30:52 T:140422083786496  NOTICE: Thread RSSReader start, auto delete: false
22:30:54 T:140420776445696  NOTICE: Thread BackgroundLoader start, auto delete: false
22:30:56 T:140420776445696  NOTICE: Thread LanguageInvoker start, auto delete: false
22:30:56 T:140420776445696  NOTICE: -->Python Interpreter Initialized<--
22:30:57 T:140420776445696  NOTICE: [trakt] Queuing for dispatch: {'action': 'manualSync', 'silent': False}

```

**Comment by razzeee** [comment]
As we move on with the new version 3.0.0 this won't be happen again. So I'll close this.
If you have any questions, let me know.
