### ISSUE TITLE
Cannot connect to trakt

### ISSUE THREAD

**Issue by danialbehzadi** [razzeee/script.trakt#206]
Notification: Cannot connect to trakt
Log:

```
22:22:52 T:1837741120 WARNING: [script.trakt] requests.packages.urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x5cfa27b0>, 'Connection to api-v2launch.trakt.tv timed out. (connect timeout=6.05)')': /auth/login
22:23:04 T:1837741120 WARNING: [script.trakt] requests.packages.urllib3.connectionpool: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x5cfa2df0>, 'Connection to api-v2launch.trakt.tv timed out. (connect timeout=6.05)')': /auth/login
22:23:10 T:1493169216  NOTICE: Thread BackgroundLoader start, auto delete: false
22:23:17 T:1837741120 WARNING: [script.trakt] requests.packages.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x5cfa2cd0>, 'Connection to api-v2launch.trakt.tv timed out. (connect timeout=6.05)')': /auth/login
22:23:29 T:1837741120   FATAL: [script.trakt] traktapi: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ConnectTimeout'>
                                            Error Contents: (MaxRetryError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /auth/login (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x5cfa2170>, 'Connection to api-v2launch.trakt.tv timed out. (connect timeout=6.05)'))",),)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.trakt/traktapi.py", line 63, in getToken
                                                auth = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "/storage/.kodi/addons/script.module.trakt/lib/trakt/interfaces/auth.py", line 10, in login
                                                'password': password
                                              File "/storage/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 89, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/storage/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 66, in request
                                                response = self.session.send(prepared, timeout=timeout)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 573, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 419, in send
                                                raise ConnectTimeout(e, request=request)
                                            ConnectTimeout: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /auth/login (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x5cfa2170>, 'Connection to api-v2launch.trakt.tv timed out. (connect timeout=6.05)'))
```

**Comment by razzeee** [comment]
Your network adapter is probably not there yet.  Read this http://forum.kodi.tv/showthread.php?tid=220547&pid=1949601#pid1949601

**Comment by danialbehzadi** [comment]
No. it's not related to network adapter status.. It's an eth cable and is ready before kodi starts

**Comment by s7eele** [comment]
so still an issue? hardware, os, versions? all other add-ons working ok? can you log into the trakt.tv website via browser? just thinking out loud

this really doesnt look like an add-on issue imho, may be time to move to forum if still a problem

**Comment by razzeee** [comment]
Network cards also need to become active even if your on a cable. 
But seems like your os is stated before kodi is called? (aka no auto start)

**Comment by danialbehzadi** [comment]
Still an issue. Openelec 5.0.5 (Kodi 14.2) on raspberry pi B+. Other addons work smoothly. I can login to trakt via browser.
The only thing I can imagine is the network firewall. Is there any way to check it?

**Comment by razzeee** [comment]
Have you activated wait on network in the openelec settings? If not please do so

**Comment by danialbehzadi** [comment]
Yes I did. Kodi waits on network before starts and there is a 15 seconds delay after kodi starts-up to start trakt script.

**Comment by razzeee** [comment]
Can you try 30 sec (the max) and let me know if anything changes?

**Comment by highhacker** [comment]
Well now trakt is totally broken in repository in kodi 14.2 . I don't like 14.2 at all there are too many things that worked on 14.1 that don't on 14.2 . They even locked out over half of the superrepo . Worst than Apple if you ask me  I'm dumping this buggy 14.2 and go back to what works 14.0 and 14.1 . The thing is trakt was working fine because I signed up with it but now some kind of foolish updates kodi did last night killed trakt and I can't even connect to the internet to restore a backup

**Comment by highhacker** [comment]
The script.trakt addon is marked as broken in repository dependencies not met version 3.0.0. So trakt is toast in kodi 14.2

**Comment by razzeee** [comment]
Well I just checked the addon under 14.2 and 15 and both were running as expected, I also uninstalled and reinstalled it.
You might want to force refresh the kodi repository.
