### ISSUE TITLE
Error Contents: No module named requests

### ISSUE THREAD

**Issue by logginuk** [razzeee/script.trakt#207]
```
10:13:05 T:2872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ImportError'>
Error Contents: No module named requests
Traceback (most recent call last):
    File "C:\Users\loggin\AppData\Roaming\Kodi\addons\script.trakt\default.py", line 6, in <module>
        from service import traktService
    File "C:\Users\loggin\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 7, in <module>
        from traktapi import traktAPI
    File "C:\Users\loggin\AppData\Roaming\Kodi\addons\script.trakt\traktapi.py", line 5, in <module>
        from trakt import Trakt, ClientError, ServerError
    File "C:\Users\loggin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\__init__.py", line 3, in <module>
        from trakt.client import TraktClient, __version__
    File "C:\Users\loggin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\client.py", line 2, in <module>
        from trakt.core.http import HttpClient
    File "C:\Users\loggin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\http.py", line 4, in <module>
        from trakt.core.request import TraktRequest
    File "C:\Users\loggin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\request.py", line 1, in <module>
        from requests import Request
ImportError: No module named requests
-->End of Python script error report<--
```

Starting getting this after upgrading to Kodi last night, did it because I was getting this from the previous XBMC Gotham install

```
22:07:31 T:3972   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.ImportError'>
Error Contents: cannot import name certs
Traceback (most recent call last):
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.trakt\default.py", line 6, in <module>
        from service import traktService
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.trakt\service.py", line 7, in <module>
        from traktapi import traktAPI
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.trakt\traktapi.py", line 5, in <module>
        from trakt import Trakt, ClientError, ServerError
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.module.trakt\lib\trakt\__init__.py", line 3, in <module>
        from trakt.client import TraktClient, __version__
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.module.trakt\lib\trakt\client.py", line 2, in <module>
        from trakt.core.http import HttpClient
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.module.trakt\lib\trakt\core\http.py", line 4, in <module>
        from trakt.core.request import TraktRequest
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.module.trakt\lib\trakt\core\request.py", line 1, in <module>
        from requests import Request
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.module.requests\lib\requests\__init__.py", line 58, in <module>
        from . import utils
    File "C:\Users\loggin\AppData\Roaming\XBMC\addons\script.module.requests\lib\requests\utils.py", line 24, in <module>
        from . import certs
ImportError: cannot import name certs
-->End of Python script error report<-- 
```

Seemed to start failing sometime Thursday (12/03) evening, upgraded to Kodi on Friday as it was still happening and hoped that would resolve any issues but alas

**Comment by razzeee** [comment]
You should install via the kodi repo or zip. That should resolve the dependencies (your system is missing requests)

**Comment by logginuk** [comment]
Was going to uninstall and reinstall the plugin but some 24hrs after the kodi upgrade, and after being on for 4-5hrs, kodi automatically did a load of updates disabling some plugins due to lack of dependencies, whilst getting some modules as well, "requests" being one of them, glad to say trakt is now working as expected.
