### ISSUE TITLE
trakt throws error on Windows

### ISSUE THREAD

**Issue by SimonHova** [razzeee/script.trakt#211]
Every time I start Kodi on my Windows 7 laptop, I get the same error message on my trakt. Upgraded from 14.1 to 14.2, uninstalled and reinstalled. Ideas?

18:02:52 T:4228   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "C:\Users\Shimon\AppData\Roaming\Kodi\addons\script.trakt\default.py", line 6, in <module>
                                                from service import traktService
                                              File "C:\Users\Shimon\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 7, in <module>
                                                from traktapi import traktAPI
                                              File "C:\Users\Shimon\AppData\Roaming\Kodi\addons\script.trakt\traktapi.py", line 5, in <module>
                                                from trakt import Trakt, ClientError, ServerError
                                              File "C:\Users\Shimon\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt__init__.py", line 3, in <module>
                                                from trakt.client import TraktClient, **version**
                                              File "C:\Users\Shimon\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\client.py", line 2, in <module>
                                                from trakt.core.http import HttpClient
                                              File "C:\Users\Shimon\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\http.py", line 4, in <module>
                                                from trakt.core.request import TraktRequest
                                              File "C:\Users\Shimon\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\request.py", line 1, in <module>
                                                from requests import Request
                                            ImportError: No module named requests
                                            -->End of Python script error report<--

**Comment by razzeee** [comment]
Your missing the requests module. 
Just reinstall script.trakt from the official kodi repo

**Comment by SimonHova** [comment]
That's odd... I thought the uninstall/reinstall would have fixed it. I installed from the github repo zip file. I will try to install from the official repo instead, let you know what happens.

**Comment by razzeee** [comment]
Well the zip should also resolve the dependencies. (be sure to not download the beta) But maybe your kodi repo is not up to date and it could not grab requests?

**Comment by SimonHova** [comment]
It looks like all the repos were there, but many of them were not enabled. Not sure what happened. I uninstalled Kodi and reinstalled, installing Kodi from the original repo as suggested (as opposed to the Github source), and it works like a pro! Thanks again!

**Comment by m-a-x-s-e-e-l-i-g** [comment]
I had the same error, have no idea why it suddenly happened. But just reinstall the requests module:
http://addons.kodi.tv/show/script.module.requests/
