### ISSUE TITLE
Unable to open sqlite database

### ISSUE THREAD

**Issue by bendernjw** [razzeee/script.trakt#215]
hi i have a kodi set up using my sql 
i get this error

18:38:41 T:3220   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: unable to open database file
                                            Traceback (most recent call last):
                                              File "C:\Users\Bender\AppData\Roaming\Kodi\addons\trakt-script.trakt-2c2bfda\default.py", line 6, in <module>
                                                from service import traktService
                                              File "C:\Users\Bender\AppData\Roaming\Kodi\addons\trakt-script.trakt-2c2bfda\service.py", line 18, in <module>
                                                class traktService:
                                              File "C:\Users\Bender\AppData\Roaming\Kodi\addons\trakt-script.trakt-2c2bfda\service.py", line 22, in traktService
                                                dispatchQueue = sqlitequeue.SqliteQueue()
                                              File "C:\Users\Bender\AppData\Roaming\Kodi\addons\trakt-script.trakt-2c2bfda\sqlitequeue.py", line 61, in **init**
                                                with self._get_conn() as conn:
                                              File "C:\Users\Bender\AppData\Roaming\Kodi\addons\trakt-script.trakt-2c2bfda\sqlitequeue.py", line 77, in _get_conn
                                                self._connection_cache[id] = sqlite3.Connection(self.path, timeout=60)
                                            OperationalError: unable to open database file
                                            -->End of Python script error report<--
18:38:41 T:3220    INFO: Python script stopped

**Comment by razzeee** [comment]
Well thats not your mysql, thats the sqlite queue failing. You may want to delete the database file from the userdata folder of the script. Should work if you restart then.

**Comment by spookypeanut** [comment]
Just to flag, I got this too in the last few days. Deleting the database sorted it, but obviously that's not ideal.

**Comment by razzeee** [comment]
Any clues why this happens? The only thing we could do is catch the error and remove the file for you.

**Comment by spookypeanut** [comment]
Not really any clue I'm afraid. I tried lots of things before I thought of looking in the logs. I don't think it's related, but another plugin had an error before the first time it happened (traceback below). 
I'll keep an eye out if it happens again. What detrimental effect would removing the file have?

15:46:58 T:1711481920  SEVERE: weather.metoffice: Traceback (most recent call last):  
                                              File "/storage/.kodi/addons/weather.metoffice/src/metoffice/utilities.py", line 22, in wrapper  
                                                return f(_args, *_kwds)  
                                              File "/storage/.kodi/addons/weather.metoffice/src/metoffice/default.py", line 37, in main  
                                                properties.observation()  
                                              File "/storage/.kodi/addons/weather.metoffice/src/metoffice/utilities.py", line 52, in wrapper  
                                                return f(_args, *_kwargs)  
                                              File "/storage/.kodi/addons/weather.metoffice/src/metoffice/properties.py", line 23, in observation  
                                                data=json.load(open(filename))  
                                              File "/storage/.kodi/addons/weather.metoffice/src/metoffice/urlcache.py", line 37, in **exit**  
                                                self.flush()  
                                              File "/storage/.kodi/addons/weather.metoffice/src/metoffice/urlcache.py", line 51, in flush  
                                                if not os.path.isfile(entry['resource']) or utilities.strptime(entry['expiry'], self.TIME_FORMAT) < datetime.utcnow():
                                              File "/storage/.kodi/addons/weather.metoffice/src/metoffice/utilities.py", line 16, in strptime
                                                return datetime.fromtimestamp(time.mktime(time.strptime(dt, fmt)))  
                                            ImportError: Failed to import _strptime because the import lockis held by another thread.

**Comment by razzeee** [comment]
Removing the file should not cause harm. As long as we're still at startup which should be the only place this error happens anyway . Otherwise it might delete commands that still haven't been processed.

**Comment by spookypeanut** [comment]
If it shouldn't cause any harm, then it probably makes sense to clean it up. But I'll leave the final decision up to you :-)

**Comment by razzeee** [comment]
Yeah, but I feel unconfortable when I can't test somethink like this. So I'm probably clsoing this.
It's documented here, people can find it. If someone finds it, he can give me a headsup and we can try some test code.

**Comment by spookypeanut** [comment]
Understood. Thanks for the help.
