### ISSUE TITLE
Crash when syncing TV shows

### ISSUE THREAD

**Issue by botchla** [Razzeee/script.trakt#22]
I'm getting the following when a sync of TV shows is running (appears to be when it's getting episode data to sync):

ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\service.py", line 273, in run
                                                sync.sync()
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 620, in sync
                                                self.__syncEpisodes()
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 357, in __syncEpisodes
                                                kodiShows = self.__kodiLoadShows()
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 87, in __kodiLoadShows
                                                show = {'title': show_col1['title'], 'ids': {'tvdb': show_col1['ids']['tvdb']}, 'year': show_col1['year'], 'seasons': []}
                                            KeyError: 'tvdb'

Running latest version of trakt addon from dev branch, and Kodi Helix on Windows 8.

**Comment by Razzeee** [comment]
@botchla 
must be some weird show, but the latest commit should fix this. please let me know.

**Comment by botchla** [comment]
@Razzeee 
Thanks! It gets much further now, but it is getting stuck when it gets to a TV show which has no TVDB entry (one I manually added to Kodi with my own .nfo files). I put that show as an exclusion, so it skips it, which helped, but now I get this with another show (one which has no episodes in Kodi):


07:47:20 T:7788   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\service.py", line 287, in run
                                                sync.sync()
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 626, in sync
                                                self.__syncEpisodes()
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 376, in __syncEpisodes
                                                traktShowsRemove = self.__compareShows(traktShows, kodiShows)
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 185, in __compareShows
                                                season_col2 = self.__getEpisodes(show_col2['seasons'], watched)
                                              File "C:\Users\Alun\AppData\Roaming\Kodi\addons\script.trakt-dev\sync.py", line 169, in __getEpisodes
                                                elif 'collected' in episode and episode['collected'] == 0:
                                            TypeError: argument of type 'NoneType' is not iterable

**Comment by Razzeee** [comment]
@botchla 
are you able to program? can you add some debugging to your version of the file, try again and post it here?

´´´
	def __getEpisodes(self, seasons, watched=False):
		data = {}
		Debug("Seasons: %s" % seasons)
		for season in seasons:
			episodes = {}
			for episode in season['episodes']:
				if watched and episode['watched'] == 0:
						continue
				elif episode['collected'] == 0:
						continue
				episodes[episode['number']] = episode['ids']
			data[season['number']] = episodes

		return data
´´´
Should be enough to get an idea

**Comment by Wipeout944** [comment]
I'm having an identical issue (same thing; shows--okay, soccer matches--added manually with my own NFOs)...

I can also try the debugging code, should it go anywhere specific in sync.py?

**Comment by BuSHari** [comment]
I`m having the same problem, and i`ve tried your code replacing.
When i`ve tried to do sync in Kodi, no progress window appeared for me, and this is what i`ve got in the log.

```
18:39:03 T:1220  NOTICE: Thread LanguageInvoker start, auto delete: false
18:39:03 T:1220    INFO: initializing python engine.
18:39:03 T:1220   DEBUG: CPythonInvoker(17, C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt\script.py): start processing
18:39:03 T:1220  NOTICE: -->Python Interpreter Initialized<--
18:39:03 T:1220   DEBUG: CPythonInvoker(17, C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt\script.py): the source file to load is "C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt\script.py"
18:39:03 T:1220   DEBUG: CPythonInvoker(17, C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt\script.py): setting the Python path to C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt;C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.module.simplejson\lib;C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.module.six\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
18:39:03 T:1220   DEBUG: CPythonInvoker(17, C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt\script.py): entering source directory C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt
18:39:03 T:1220   DEBUG: CPythonInvoker(17, C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt\script.py): instantiating addon using automatically obtained id of "script.trakt" dependent on version 2.1.0 of the xbmc.python api
18:39:03 T:1220  NOTICE: [trakt] Queuing for dispatch: {'action': 'manualSync', 'silent': False, 'library': 'all'}
18:39:04 T:1220    INFO: CPythonInvoker(17, C:\Users\iBuSH\AppData\Roaming\Kodi\addons\script.trakt\script.py): script successfully run
18:39:04 T:1220    INFO: Python script stopped
18:39:04 T:1220   DEBUG: Thread LanguageInvoker 1220 terminating
```

**Comment by Wipeout944** [comment]
OK, when running sync with debug code, here's a logfile: http://xbmclogs.com/show.php?id=406326

Here's the part right before the error:

08:43:19 T:5388  NOTICE: [trakt] shows [{'seasons': [{'episodes': [{'title': u'1x02. Portland Thorns v. Seattle Reign', 'season': 1, 'ids': {'tvdb': u'', 'episodeid': 1310}, 'number': 2, 'watched_at': u'2013-05-24 07:45:31', 'collected_at': u'2013-04-25 09:25:20', 'watched': 1}, {'title': u'1x17. Portland Thorns v. Chicago Red Stars', 'season': 1, 'ids': {'tvdb': u'', 'episodeid': 1363}, 'number': 17, 'watched_at': u'2015-01-01 19:37:18', 'collected_at': u'2013-07-29 21:01:22', 'watched': 1}, {'title': u'1x19. Portland Thorns vs. FC Kansas City', 'season': 1, 'ids': {'tvdb': u'', 'episodeid': 1364}, 'number': 19, 'watched_at': u'2015-01-01 19:37:18', 'collected_at': u'2013-08-10 18:16:01', 'watched': 1}, {'title': u'1x24. Portland Thorns vs. FC Kansas City (Semifinal)', 'season': 1, 'ids': {'tvdb': u'', 'episodeid': 1373}, 'number': 24, 'watched_at': u'2015-01-01 19:37:18', 'collected_at': u'2013-09-02 10:49:50', 'watched': 1}, {'title': u'1x25. Portland Thorns vs. Western New York Flash (Final)', 'season': 1, 'ids': {'tvdb': u'', 'episodeid': 1374}, 'number': 25, 'watched_at': u'2015-01-01 19:37:18', 'collected_at': u'2013-09-02 09:30:03', 'watched': 1}], 'number': 1}], 'year': 0, 'ids': {}, 'title': u'Portland Thorns'}]
08:43:19 T:5388   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 287, in run
                                                sync.sync()
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 627, in sync
                                                self.__syncEpisodes()
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 381, in __syncEpisodes
                                                traktShowsUpdate = self.__compareShows(kodiShows, traktShows, watched=True)
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 231, in __compareShows
                                                show = {'title': show_col1['title'], 'ids': {'tvdb': show_col1['ids']['tvdb']}, 'year': show_col1['year'], 'seasons': []}
                                            KeyError: 'tvdb'

**Comment by Razzeee** [comment]
We're mixing up two errors here.
@BuSHari this only happens if theres a problem with the files you copied, try installing it from zip

@Wipeout944 Can you retry with the latest version? The additional log would only be interesting if you got the error @botchla mentioned last

**Comment by Wipeout944** [comment]
You got it. Weird, I was getting that exact error and after messing with the debug code, that one went away and the other message (above came back). I'll try that version and report back.

**Comment by Wipeout944** [comment]
@Razzeee OK, new error with the latest:
10:04:41 T:8632   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 287, in run
                                                sync.sync()
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 628, in sync
                                                self.__syncEpisodes()
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 383, in __syncEpisodes
                                                self.__traktUpdateEpisodes(traktShowsUpdate)
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 296, in __traktUpdateEpisodes
                                                Debug("[Episodes Sync] Episodes updated: %s" % self.__getShowAsString(show, short=True))
                                              File "C:\Users\dlloyd\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 160, in __getShowAsString
                                                return "%s [tvdb: %s] - %s" % (show['title'], show['ids']['tvdb'], ", ".join(p))
                                            TypeError: string indices must be integers

Here's full debug log: http://xbmclogs.com/show.php?id=406404

**Comment by Razzeee** [comment]
@Wipeout944 
next try

**Comment by Wipeout944** [comment]
Nailed it. It correctly synced up my TV shows (it thinks I just watched 23.7k minutes of TV this week, but that's a separate issue!).

**Comment by Razzeee** [comment]
I'll close this as you had the same error as the starting post somewhere along the line. 
@Wipeout944 watched status is already mentioned in another issue, might want to watch that.
Thanks!
