### ISSUE TITLE
Trakt wont sync movies

### ISSUE THREAD

**Issue by azgul** [razzeee/script.trakt#238]
Hey guys,

I recently returned to Kodi+Trakt from Plex and as such I'd like to sync my watched status again, but when trying to do so - both when doing so manually as well automatically after library update - it fails with the following error message in kodi.log

```
18:34:30 T:10368   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\threading.py", line 810, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\Martin\AppData\Roaming\Kodi\addons\script.trakt\service.py", line 328, in run
                                                sync.sync()
                                              File "C:\Users\Martin\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 930, in sync
                                                self.__syncMovies()
                                              File "C:\Users\Martin\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 842, in __syncMovies
                                                self.__addMoviesToKodiWatched(traktMovies, kodiMovies)
                                              File "C:\Users\Martin\AppData\Roaming\Kodi\addons\script.trakt\sync.py", line 769, in __addMoviesToKodiWatched
                                                chunked_movies = utilities.chunks([{"jsonrpc": "2.0", "method": "VideoLibrary.SetMovieDetails", "params": {"movieid": kodiMoviesToUpdate[i]['movieid'], "playcount": kodiMoviesToUpdate[i]['plays'], "lastplayed": utilities.convertUtcToDateTime(kodiMoviesToUpdate[i]['last_watched_at'])}, "id": i} for i in range(len(kodiMoviesToUpdate))], chunksize)
                                              File "C:\Users\Martin\AppData\Roaming\Kodi\addons\script.trakt\utilities.py", line 447, in convertUtcToDateTime
                                                local = utc.astimezone(tzlocal())
                                              File "C:\Users\Martin\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz.py", line 113, in utcoffset
                                                if self._isdst(dt):
                                              File "C:\Users\Martin\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz.py", line 157, in _isdst
                                                return time.localtime(timestamp+time.timezone).tm_isdst
                                            ValueError: (22, 'Invalid argument')
```

Let me know if you need more info.

Thanks,

Martin

**Comment by razzeee** [comment]
Please check your trakt account if there are movies/shows collected/watched outside of the 1980-2038 timespan.
Then check if there are any movies watched outside of that timespan.
Remove these and everything should be fine.

**Comment by azgul** [comment]
Sigh. There's a bunch of movies that are marked as watched on epoch. I'll fix that and I guess that fixes this issue too. Weird stuff.

edit: yeah - it did.

**Comment by razzeee** [comment]
I'll try to add a safe guard for that, but I don't know when or if I can find some time.
https://github.com/Razzeee/script.trakt/issues/214
