### ISSUE TITLE
Problem when default action was list before installing the new script.trakt

### ISSUE THREAD

**Issue by magnumpci** [Razzeee/script.trakt#25]
Trakt will start on my Win7 box (stalls on TV syncing, however) but immediately fails on FireTV

Full log :http://xbmclogs.com/show.php?id=404846

07:19:50 T:1680596896  NOTICE: -->Python Interpreter Initialized<--
07:19:50 T:1680596896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (1,)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt-dev/script.py", line 243, in <module>
                                                Main()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt-dev/script.py", line 46, in Main
                                                args = __getArguments()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt-dev/script.py", line 33, in __getArguments
                                                data = {'action': default_actions[default]}
                                            KeyError: (1,)
                                            -->End of Python script error report<--

**Comment by Razzeee** [comment]
Should be fixed, pleas let me know!
