### ISSUE TITLE
Fatal error appearing in log file

### ISSUE THREAD

**Issue by thwaller** [razzeee/script.trakt#275]
I am receiving this error in my log file. I am using version 3.1.2 on Kodi v16. OS is Ubuntu v14.04. All updates and upgrades done to Kodi, including its addons, and OS. Please advise what additional info may be needed to diagnose.

FATAL: [script.trakt] service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'KeyError'>
                                            Error Contents: ('id',)
                                            Traceback (most recent call last):
                                              File "/home/brian/.kodi/addons/script.trakt-master/service.py", line 42, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/home/brian/.kodi/addons/script.trakt-master/scrobbler.py", line 234, in playbackEnded
                                                self.__scrobble('stop')
                                              File "/home/brian/.kodi/addons/script.trakt-master/scrobbler.py", line 274, in __scrobble
                                                response['episode']['episodeid'] = self.curVideo['id']
                                            KeyError: 'id'
                                            -->End of Python script error report<--

**Comment by thwaller** [comment]
There are at least a dozen of those errors, all stating the same but referencing different lines.
