### ISSUE TITLE
Trakt Error

### ISSUE THREAD

**Issue by shrubz** [razzeee/script.trakt#297]
Hi

I have Kodi setup on Nvidia Shield using MySQL on Synology DS

I get the message Trakt error whenever I install the addon. Log is below

23:58:51 T:1473227056   ERROR: bool CDatabase::ExecuteQuery(const string&) - failed to execute query 'insert into package(id, addonID, filename, hash)values(NULL, 'script.trakt', 'special://home/addons/packages/script.trakt-3.1.4.zip', '4E34D3C1EC7F91245D175E70E96DDFFA')'
23:58:53 T:1424591152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: unable to open database file
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/default.py", line 6, in <module>
                                                from service import traktService
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/service.py", line 23, in <module>
                                                class traktService:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/service.py", line 27, in traktService
                                                dispatchQueue = sqlitequeue.SqliteQueue()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/sqlitequeue.py", line 60, in **init**
                                                with self._get_conn() as conn:
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/sqlitequeue.py", line 76, in _get_conn
                                                self._connection_cache[id] = sqlite3.Connection(self.path, timeout=60)
                                            OperationalError: unable to open database file
                                            -->End of Python script error report<--

**Comment by razzeee** [comment]
I think I've seen this error before, but it vanished into thin air, the next time the user restarted. Has yours been solved?
