### ISSUE TITLE
freeze under movie progress syncronisation (only hungaryan localization)

### ISSUE THREAD

**Issue by Szurgent** [razzeee/script.trakt#311]
My kodi freezed totaly under the movie progress syncronisation with following error:

07:07:04 354.621033 T:1457255344   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
                                                self.run()
                                              File "/home/xbian/.kodi/addons/script.trakt/service.py", line 334, in run
                                                sync.sync()
                                              File "/home/xbian/.kodi/addons/script.trakt/sync.py", line 56, in sync
                                                syncMovies.SyncMovies(self, progress)
                                              File "/home/xbian/.kodi/addons/script.trakt/syncMovies.py", line 43, in __init**
                                                self.__addMovieProgressToKodi(traktMoviesProgress, kodiMovies, 81, 91)
                                              File "/home/xbian/.kodi/addons/script.trakt/syncMovies.py", line 291, in __addMovieProgressToKodi
                                                self.sync.UpdateProgress(toPercent, line2=kodiUtilities.getString(32128) % len(kodiMoviesToUpdate))
                                            TypeError: not enough arguments for format string

trakt script version: 3.1.7

I think because the hungaryan translation is bugy:
en: Playback progress updated for %i movie(s) in Kodi
hu: (%i/%i) film lejátszási folyamatának frissítése
(unwanted parameter)

1: i fixed the translation to following on transifex page /xbmc addon/script-trakt:

fixed hu: %i film lejátszási folyamata frissítve

2: try improve the exceptionhandling if possible, to prevent the totaly freeze.

thx, sorry my english.

**Comment by razzeee** [comment]
Hey, 

have you also fixed this one on transifex?

msgctxt "#32127"
msgid "Updating %i of %i movie(s) playback progress in Kodi"
msgstr "(%i/%i) film lejátszási folyamatának frissítése"

Thx!

**Comment by Szurgent** [comment]
Hey,
no, couse it didnt need fixing. In this sentence there was 2x %i, so its fine. In the one i fixed there was 1 %i in the original english senence and 2 %i in the hungarian sentence. Is it OK then?
Thx :)

**Comment by razzeee** [comment]
Yes, seems like I overlooked that one.
