### ISSUE TITLE
Scrobbler does not start properly 

### ISSUE THREAD

**Issue by jedo75** [razzeee/script.trakt#320]
When starting movie in Exodus, scrobbler does not start  : 
system:
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:    8.6
Codename:   jessie

Exodus : 2.0.12

python --version
Python 2.7.9

FATAL: [script.trakt] service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("initializer for ctype 'int(_)(int, X509_STORE_CTX *)' must be a pointer to same type, not cdata 'int(_)(int, X509_STORE_CTX _)'",)
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/script.trakt/service.py", line 40, in _dispatch
                                                self.scrobbler.playbackStarted(data)
                                              File "/home/kodi/.kodi/addons/script.trakt/scrobbler.py", line 165, in playbackStarted
                                                result = self.__scrobble('start')
                                              File "/home/kodi/.kodi/addons/script.trakt/scrobbler.py", line 278, in __scrobble
                                                response = self.traktapi.scrobbleEpisode(self.traktShowSummary, self.curVideoInfo, watchedPercent, status)
                                              File "/home/kodi/.kodi/addons/script.trakt/traktapi.py", line 151, in scrobbleEpisode
                                                progress=percent)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 35, in wrap
                                                return func(_args, *_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/**init**.py", line 19, in wrap
                                                return func(_args, *_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/interfaces/scrobble.py", line 49, in start
                                                *_kwargs
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/**init**.py", line 35, in wrap
                                                return func(_args, *_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/**init**.py", line 19, in wrap
                                                return func(_args, *_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/interfaces/scrobble.py", line 36, in action
                                                authenticated=kwargs.get('authenticated', None)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 129, in post
                                                return self.request('POST', path, params, data, *_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 84, in request
                                                return self.send(prepared)
                                              File "/home/kodi/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 102, in send
                                                response = self.session.send(request, timeout=timeout)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 576, in send
                                                r = adapter.send(request, *_kwargs)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 376, in send
                                                timeout=timeout
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
                                                body=body, headers=headers)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
                                                self._validate_conn(conn)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
                                                conn.connect()
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connection.py", line 252, in connect
                                                ssl_version=resolved_ssl_version)
                                              File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 279, in ssl_wrap_socket
                                                ctx.set_verify(_openssl_verify[cert_reqs], _verify_callback)
                                              File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 543, in set_verify
                                                _lib.SSL_CTX_set_verify(self._context, mode, self._verify_callback)
                                            TypeError: initializer for ctype 'int(_)(int, X509_STORE_CTX *)' must be a pointer to same type, not cdata 'int(_)(int, X509_STORE_CTX *)'
                                            -->End of Python script error report<--

**Comment by razzeee** [comment]
Hey, please have a look at https://github.com/trakt/script.trakt/issues/243
