### ISSUE TITLE
No sync if path contains special character(s) in ExcludePathX setting

### ISSUE THREAD

**Issue by Cocotus** [razzeee/script.trakt#322]
I have latest Kodi 17 (LibreElec) Krypton running  and right now having problems getting anything to sync to trakt.tv (worked before). 

This is Kodilog:

```
21:49:06 T:140231798396672   ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/.kodi/addons/script.trakt/service.py", line 334, in run
                                                sync.sync()
                                              File "/storage/.kodi/addons/script.trakt/sync.py", line 56, in sync
                                                syncMovies.SyncMovies(self, progress)
                                              File "/storage/.kodi/addons/script.trakt/syncMovies.py", line 19, in __init__
                                                kodiMovies = self.__kodiLoadMovies()
                                              File "/storage/.kodi/addons/script.trakt/syncMovies.py", line 67, in __kodiLoadMovies
                                                kodi_movies = kodiUtilities.kodiRpcToTraktMediaObjects(data)
                                              File "/storage/.kodi/addons/script.trakt/kodiUtilities.py", line 191, in kodiRpcToTraktMediaObjects
                                                movieObject = kodiRpcToTraktMediaObject('movie', movie, mode)
                                              File "/storage/.kodi/addons/script.trakt/kodiUtilities.py", line 139, in kodiRpcToTraktMediaObject
                                                if checkExclusion(data.pop('file')):
                                              File "/storage/.kodi/addons/script.trakt/kodiUtilities.py", line 90, in checkExclusion
                                                if fullpath.startswith(ExcludePath):
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 59: ordinal not in range(128)
```

this is my setting file from userdata folder:

```
<settings>
    <setting id="Auth_Info" value="" />
    <setting id="ExcludeHTTP" value="false" />
    <setting id="ExcludeLiveTV" value="true" />
    <setting id="ExcludePath" value="smb://BIBRASSERVER/Media_3/Serien/Aktenzeichen XY ... ungelöst/" />
    <setting id="ExcludePath10" value="" />
    <setting id="ExcludePath11" value="" />
    <setting id="ExcludePath12" value="" />
    <setting id="ExcludePath2" value="nfs://192.168.2.200/Videos/Movies/" />
.....
```

Seems to me, there's a problem with special characters in exclusion setting? Any chance to fix this? I tried without this exclusion and sync worked :)

**Comment by razzeee** [comment]
I started looking at this yesterday, but I want to fix it right. It feels like this part of the code falls over every four months, so I will take some time to investigate this time around. Please be patient :)

**Comment by Cocotus** [comment]
That sounds good, take your time! Meanwhile I removed the exclusion from setting and everything's working smoothly. Tell me if you need other information or if I can test something for you.
