### ISSUE TITLE
Traceback: ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by fernandog** [razzeee/script.trakt#394]
@Razzeee
I'm getting this traceback in logs and I can' scrobble or rate

```xml
<addon id="script.trakt" name="Trakt" version="3.1.12" provider-name="Trakt.tv, Razzeee">
	<requires>
        <import addon="xbmc.python" version="2.24.0"/>
        <import addon="script.module.simplejson" version="3.3.0"/>
        <import addon="script.module.trakt" version="2.12.0"/>
        <import addon="script.module.dateutil" version="2.4.2"/>
        <import addon="script.module.addon.signals" version="0.0.1"/>
	</requires>
```

BTW imho you should add trakt log version to logs

```
10:23:40.159 T:1709380592   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: bad marshal data (unknown type code)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.trakt/default.py", line 6, in <module>
                                                from resources.lib.service import traktService
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/service.py", line 19, in <module>
                                                from resources.lib.traktapi import traktAPI
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/traktapi.py", line 8, in <module>
                                                from trakt import Trakt
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/__init__.py", line 3, in <module>
                                                from trakt.client import TraktClient
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/client.py", line 5, in <module>
                                                from trakt.core.http import HttpClient
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 8, in <module>
                                                from trakt.core.request import TraktRequest
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/request.py", line 3, in <module>
                                                from requests import Request
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 52, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/__init__.py", line 27, in <module>
                                                from . import urllib3
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/__init__.py", line 8, in <module>
                                                from .connectionpool import (
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py", line 11, in <module>
                                                from .exceptions import (
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/exceptions.py", line 2, in <module>
                                                from .packages.six.moves.http_client import (
                                            ValueError: bad marshal data (unknown type code)
                                            -->End of Python script error report<--
```

**Comment by razzeee** [comment]
Might be a osmc problem, due to wrongly build python.

**Comment by samnazarko** [comment]
We use Debian's Python in OSMC so I doubt there is an issue there.

**Comment by razzeee** [comment]
@fernandog can you do this? https://stackoverflow.com/a/30861494/2859813

So basically remove the *.pyc and try again?

**Comment by samnazarko** [comment]
@fernandog also reports this with another add-on.

We have had no reports on our forum. I think @fernandog's SD card is corrupt. I recommend a reinstall or new SD card.

**Comment by fernandog** [comment]
@Razzeee that with a reboot worked. Closing

**Comment by razzeee** [comment]
Good, glad to hear. But not sure how that happens in the first place. Would be nice to eliminate the problem.
