### ISSUE TITLE
Script Won't Load on Windows Store Version of Kodi

### ISSUE THREAD

**Issue by jbienz** [razzeee/script.trakt#397]
I do not know if this is related to Windows Store, but ever since I switched to that version I've not been able to get the Trakt plugin to work. I finally went through capturing a log and below seems to be the most relevant data. Full log here: [kodilog.txt](https://github.com/trakt/script.trakt/files/1243499/kodilog.txt)

16:29:55.513 T:8344   FATAL: [script.trakt] __main__: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ImportError'>
                                            Error Contents: ('No module named uts46data',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.trakt\default.py", line 21, in <module>
                                                traktService().run()
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\service.py", line 102, in run
                                                globals.traktapi = traktAPI()
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\traktapi.py", line 60, in __init__
                                                self.login()
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\traktapi.py", line 65, in login
                                                code = Trakt['oauth/device'].code()
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\interfaces\oauth\device.py", line 28, in code
                                                'client_id': client_id
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\http.py", line 154, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\http.py", line 103, in request
                                                prepared = request.prepare()
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\request.py", line 39, in prepare
                                                return self.request.prepare()
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 257, in prepare
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 302, in prepare
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 378, in prepare_url
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\idna\core.py", line 340, in encode
                                              File "C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\idna\core.py", line 309, in uts46_remap
                                            ImportError: No module named uts46data
                                            -->End of Python script error report<--
16:30:01.261 T:4904   ERROR: XFILE::CDirectory::GetDirectory - Error getting
16:36:05.299 T:7784   ERROR: Previous line repeats 2 times.

I am attaching my full log file for this error. The result is that the authentication popup never shows and clicking on the "How do I authorize" link under Config has no effect.

**Comment by razzeee** [comment]
Most likely a kodi problem, not much we can do

**Comment by afedchin** [comment]
check that `C:\Users\Admin\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\idna\uts46data.py` exists on your machine

**Comment by razzeee** [comment]
It's in the version that the kodi repo delivers fyi: https://github.com/xbmc/repo-scripts/blob/gotham/script.module.requests/lib/requests/packages/idna/uts46data.py

So either the download somehow failed or your virus scan thought it's bad?

**Comment by jbienz** [comment]
Thanks to you both. In that location uts46data.py does not exist, but I'm not entirely sure that it's supposed to. I know @Razzeee points out that it's in the XBMC repo, but there are **NO** .py files in that folder at all. There are .pyo files, which appear to be compiled pyton files. In that folder I see __init__, core, idnadata and intranges (all ending with .pyo). I don't see uts46data.pyo, but I'm wondering if that's idnadata.pyo.

Any thoughts?

![idna](https://user-images.githubusercontent.com/2062886/29620791-874afcea-87e4-11e7-980e-8d3b1d50835a.PNG)

**Comment by jbienz** [comment]
P.S. I did look in the repot:

https://github.com/xbmc/repo-scripts/tree/gotham/script.module.requests/lib/requests/packages/idna

And I see there are both idnadata.py and uts46data.py. So it _does_ appear that uts45data.pyo should be in that folder on my machine. 

Problem is that I've gone into the AddOn manager in Kodi and reinstalled scripts.modules.requests from the repository multiple times and it's still not there. There are also no warnings in my antivirus (which is just standard Windows Defender).

Now, here's the weirdest part. I just went and updated requests again (Kodi -> System -> AddOns -> Manage Dependencies). And right after I updated it, the Trackt popup showed up and I was able to authenticate. **But there is still no uts46data.py in the requests folder on my machine**.

**Comment by razzeee** [comment]
Your also missing compat and codec files in the Screenshot.

**Comment by jbienz** [comment]
According to the screenshot, yes. But I don't know if the pyo compiler can combine files or something. Like I said, all of the sudden Trakt started working again despite these files being missing. You can feel free to close this now unless you want to keep researching it with me. If it starts happening again I can open it back up.
