### ISSUE TITLE
MemoryError crashing Kodi

### ISSUE THREAD

**Issue by Lunatixz** [razzeee/script.trakt#408]
```
ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "D:\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "D:\Kodi\portable_data\addons\script.trakt\resources\lib\service.py", line 335, in run
                                                sync.sync()
                                              File "D:\Kodi\portable_data\addons\script.trakt\resources\lib\sync.py", line 56, in sync
                                                syncMovies.SyncMovies(self, progress)
                                              File "D:\Kodi\portable_data\addons\script.trakt\resources\lib\syncMovies.py", line 34, in __init__
                                                self.__addMoviesToTraktCollection(kodiMovies, traktMovies, 37, 47)
                                              File "D:\Kodi\portable_data\addons\script.trakt\resources\lib\syncMovies.py", line 124, in __addMoviesToTraktCollection
                                                addTraktMovies = copy.deepcopy(traktMovies)
                                              File "D:\Kodi\system\python\Lib\copy.py", line 163, in deepcopy
                                                y = copier(x, memo)
                                              File "D:\Kodi\system\python\Lib\copy.py", line 230, in _deepcopy_list
                                                y.append(deepcopy(a, memo))
                                              File "D:\Kodi\system\python\Lib\copy.py", line 163, in deepcopy
                                                y = copier(x, memo)
                                              File "D:\Kodi\system\python\Lib\copy.py", line 257, in _deepcopy_dict
                                                y[deepcopy(key, memo)] = deepcopy(value, memo)
                                              File "D:\Kodi\system\python\Lib\copy.py", line 163, in deepcopy
                                                y = copier(x, memo)
                                              File "D:\Kodi\system\python\Lib\copy.py", line 257, in _deepcopy_dict
                                                y[deepcopy(key, memo)] = deepcopy(value, memo)
                                              File "D:\Kodi\system\python\Lib\copy.py", line 193, in deepcopy
                                                _keep_alive(x, memo) # Make sure x lives at least as long as d
                                              File "D:\Kodi\system\python\Lib\copy.py", line 278, in _keep_alive
                                                memo[id(memo)].append(x)
                                            MemoryError
```

**Comment by razzeee** [comment]
Was there any new development here?

**Comment by Lunatixz** [comment]
I was unsuccessful in repeating this error...  I'll keep an eye out for it. FYI most of the time this has to do with the recursive loop within the deepcopy.
