### ISSUE TITLE
Kodi trakt.tv addon won't Scrobble after a period of time

### ISSUE THREAD

**Issue by Handyone** [razzeee/script.trakt#441]
Kodi trakt.tv addon won't Scrobble after a period of time.
If I start watching a tv show episode then stop it right after it will scrobble normally but if I let it run it's full length I get the error below and it won't scrobble.
`FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ConnectionError'>
                                            Error Contents: (ProtocolError('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')),)
                                            Traceback (most recent call last):
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\service.py", line 44, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\scrobbler.py", line 248, in playbackEnded
                                                self.__scrobble('stop')
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\scrobbler.py", line 288, in __scrobble
                                                response = self.traktapi.scrobbleEpisode(self.traktShowSummary, self.curVideoInfo, watchedPercent, status)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\traktapi.py", line 163, in scrobbleEpisode
                                                progress=percent)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\interfaces\base\__init__.py", line 38, in wrap
                                                return func(*args, **kwargs)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\interfaces\base\__init__.py", line 22, in wrap
                                                return func(*args, **kwargs)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\interfaces\scrobble.py", line 448, in stop
                                                **kwargs
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\interfaces\base\__init__.py", line 38, in wrap
                                                return func(*args, **kwargs)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\interfaces\base\__init__.py", line 22, in wrap
                                                return func(*args, **kwargs)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\interfaces\scrobble.py", line 130, in action
                                                'validate_token'
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\http.py", line 154, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\http.py", line 109, in request
                                                return self.send(prepared)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\http.py", line 127, in send
                                                response = self.session.send(request, timeout=timeout)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 618, in send
                                                r = adapter.send(request, **kwargs)
                                              File "C:\Users\WIN10-PC\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\adapters.py", line 490, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))
                                            -->End of Python script error report<--
`

**Comment by nunojsa** [comment]
Hi, it seems im having a similar issue:

`17:24:01.080 T:3854299904   FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'ConnectionError'>
                                            Error Contents: (ProtocolError('Connection aborted.', error(104, 'Connection reset by peer')),)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/service.py", line 44, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 248, in playbackEnded
                                                self.__scrobble('stop')
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 288, in __scrobble
                                                response = self.traktapi.scrobbleEpisode(self.traktShowSummary, self.curVideoInfo, watchedPercent, status)
                                              File "/home/osmc/.kodi/addons/script.trakt/resources/lib/traktapi.py", line 163, in scrobbleEpisode
                                                progress=percent)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 38, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 22, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/scrobble.py", line 448, in stop
                                                **kwargs
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 38, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/base/__init__.py", line 22, in wrap
                                                return func(*args, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/interfaces/scrobble.py", line 130, in action
                                                'validate_token'
File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 154, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 109, in request
                                                return self.send(prepared)
                                              File "/home/osmc/.kodi/addons/script.module.trakt/lib/trakt/core/http.py", line 127, in send
                                                response = self.session.send(request, timeout=timeout)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 622, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/home/osmc/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 495, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
                                            -->End of Python script error report<--
`

Does trakt has any issue when used together with mysql or a library shared with NFS?

**Comment by nunojsa** [comment]
Some more info. The odd thing (at least for me) is that if i fast forward the video until the end the addon works fine. Or even when the episode ends, if i fast forward the video some seconds and then stop it, it works. But if i let the video run normally until the end and exiting alone, it fails...

Any help would be appreciated...

**Comment by vincewinkel** [comment]
Also have this exact same problem, on Kodi 18.2. How to solve this?

**Comment by razzeee** [comment]
Please create a log as stated in the readme. I'm closing this issue until somebody does that.
