### ISSUE TITLE
Not syncing collection

### ISSUE THREAD

**Issue by Zipster79** [razzeee/script.trakt#489]
I am getting this error when trying to sync between kodi and trakt, I am guessing its because of a TV Show I have added? Is there anyway of working out which one it is? and also what is the error with the TV show? Is there an episode wrongly dated? TV Show wrongly dated? Thanks in advance

`ERROR: Exception in thread trakt-sync:
                                            Traceback (most recent call last):
                                              File "C:\Program Files\Kodi\system\python\Lib\threading.py", line 801, in __bootstrap_inner
                                                self.run()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\service.py", line 328, in run
                                                sync.sync()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\sync.py", line 65, in sync
                                                syncEpisodes.SyncEpisodes(self, progress)
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\syncEpisodes.py", line 30, in __init__
                                                traktShowsCollected, traktShowsWatched, traktShowsRated, traktEpisodesRated = self.__traktLoadShows()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\syncEpisodes.py", line 169, in __traktLoadShows
                                                show = show.to_dict()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\objects\show.py", line 179, in to_dict
                                                for season in self.seasons.values()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\objects\season.py", line 76, in to_dict
                                                result = self.to_identifier()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\objects\season.py", line 60, in to_identifier
                                                for episode in self.episodes.values()
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\objects\episode.py", line 98, in to_dict
                                                'last_watched_at': to_iso8601_datetime(self.last_watched_at),
                                              File "C:\Users\***\AppData\Roaming\Kodi\addons\script.module.trakt\lib\trakt\core\helpers.py", line 152, in to_iso8601_datetime
                                                return value.strftime('%Y-%m-%dT%H:%M:%S') + '.000-00:00'
                                            ValueError: year=202 is before 1900; the datetime strftime() methods require year >= 1900`

**Comment by Zipster79** [comment]
I found it! There is an episode of American Pickers (S21E10) on trakt which is dated as '3 January 0202' which messed everything up!
