### ISSUE TITLE
Openelec SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by p00chie** [Razzeee/script.trakt#49]
I tested the most recent master and dev branches with kodi on opelec rc3.
I installed six and requests.
After reboot i get this log:
03:48:11 T:1721357376   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.SSLError'>
                                            Error Contents: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.trakt-dev/default.py", line 13, in <module>
                                                traktService().run()
                                              File "/storage/.kodi/addons/script.trakt-dev/service.py", line 101, in run
                                                globals.traktapi = traktAPI()
                                              File "/storage/.kodi/addons/script.trakt-dev/traktapi.py", line 66, in __init__
                                                self.getToken()
                                              File "/storage/.kodi/addons/script.trakt-dev/traktapi.py", line 84, in getToken
                                                self.__token = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "/storage/.kodi/addons/script.trakt-dev/trakt/interfaces/auth.py", line 10, in login
                                                'password': password
                                              File "/storage/.kodi/addons/script.trakt-dev/trakt/core/http.py", line 72, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/storage/.kodi/addons/script.trakt-dev/trakt/core/http.py", line 49, in request
                                                response = self.session.send(prepared)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 569, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 420, in send
                                                raise SSLError(e, request=request)
                                            SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
                                            -->End of Python script error report<--

**Comment by p00chie** [comment]
I fixed it by setting
        #: SSL Verification default.
        self.verify = True
to False
In sessions.py
in Kodi\addons\script.module.requests\lib\requests

**Comment by Razzeee** [comment]
@fuzeman
can you have a look here too?

**Comment by p00chie** [comment]
Maybe it had something to do that i didn't set up a timeserver on kodi. so the system thought that it was was 1970. I think i saw something that the auth with ssl required a date of at least 1.1.2014

**Comment by fuzeman** [comment]
Yeah, SSL certificate verification does require a correct system date/time.

Guessing this can be closed now?
