### ISSUE TITLE
Error scrobbling specials outside of Kodi library.

### ISSUE THREAD

**Issue by ghost** [razzeee/script.trakt#490]
Hello.

I have noticed a what seems to be a bug and am after some advice.

I am writing myself a little py3 addon to learn some code and have been using some of my local files to test with. I have a few TV show specials so the infolabels are set at "season": 0 "episode": 1

This shows in the kodi player as SE1 on the top left, that's also how it shows via the kodi library on playback.

However this will not scrobble to trakt as the episode is "S1" which i assume stands for Episode Special 1.

This fails when script.trakt trys to get the episode from the player infolabel with the following.

```2020-01-30 11:33:28.180 T:31272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'ValueError'>
                                            Error Contents: invalid literal for int() with base 10: 'S1'
                                            Traceback (most recent call last):
                                              File "C:\Users\Thomas\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\service.py", line 423, in onAVStarted
                                                self.type, data = kodiUtilities.getInfoLabelDetails(result)
                                              File "C:\Users\Thomas\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\kodiUtilities.py", line 316, in getInfoLabelDetails
                                                episode = int(xbmc.getInfoLabel('VideoPlayer.Episode') or '-1')
                                            ValueError: invalid literal for int() with base 10: 'S1'
                                            -->End of Python script error report<--```

script.trakt is looking for an integer there. 

It looks to me like Kodis player is marking any episode from season 0 as S(NUM) as its a special episode and leaving the season label as bank, but this then breaks as script.trakt is never expecting this.

Could you please advise?

**Comment by ghost** [comment]
I have found that setting the Kodi infolabels to:

`{'season': 0, 'episode': 1}`

results in the kodi player returning the following for the season and episode infolabels
```
2020-01-30 11:54:13.477 T:14612   DEBUG: [script.trakt] resources.lib.kodiUtilities: getInfoLabelDetails - season is
2020-01-30 11:54:13.478 T:14612   DEBUG: [script.trakt] resources.lib.kodiUtilities: getInfoLabelDetails - episode is S1
```

The above is from here:

```        # do a deeper check to see if we have enough data to perform scrobbles
        logger.debug("getInfoLabelDetails - Started playing a non-library file, checking available data.")
        logger.debug(f"getInfoLabelDetails - season is {xbmc.getInfoLabel('VideoPlayer.Season')}")
        logger.debug(f"getInfoLabelDetails - episode is {xbmc.getInfoLabel('VideoPlayer.Episode')}")

        season = int(xbmc.getInfoLabel('VideoPlayer.Season') or '-1')
        episode = int(xbmc.getInfoLabel('VideoPlayer.Episode') or '-1')
        showtitle = (xbmc.getInfoLabel('VideoPlayer.TVShowTitle') or xbmc.getInfoLabel('VideoPlayer.Title'))
        title = xbmc.getInfoLabel('VideoPlayer.EpisodeName')
        year = (xbmc.getInfoLabel('VideoPlayer.Year') or utilities.regex_year(showtitle)[1])
        video_ids = xbmcgui.Window(10000).getProperty('script.trakt.ids')
        if video_ids:
            data['video_ids'] = json.loads(video_ids)
        logger.debug("getInfoLabelDetails info - ids: %s, showtitle: %s, Year: %s, Season: %s, Episode: %s" % (video_ids, showtitle, year, season, episode))
```

Thats line 314 in kodiUtilities.py

Because nothing is returned for season and E1 for the episode script.trakt then thinks its a random movie and starts scrobbling Lagend of Rabbit in my case.

**Comment by ghost** [comment]
To fix the issue and allow the special episodes to be scrobbled to trakt the following change to KodiUtilities.py allows that to happen.

Original code

```       
        # do a deeper check to see if we have enough data to perform scrobbles
        logger.debug("getInfoLabelDetails - Started playing a non-library file, checking available data.")
        season = int(xbmc.getInfoLabel('VideoPlayer.Season') or '-1')
        episode = int(xbmc.getInfoLabel('VideoPlayer.Episode') or '-1')
```
https://github.com/trakt/script.trakt/blob/master/resources/lib/kodiUtilities.py#L313

Changing the above to
```
        # do a deeper check to see if we have enough data to perform scrobbles
        logger.debug("getInfoLabelDetails - Started playing a non-library file, checking available data.")
        season = int(xbmc.getInfoLabel('VideoPlayer.Season') or '-1')
        # we cannot convert to int here incase os a sepcial episode. That starts with S.
        episode = xbmc.getInfoLabel('VideoPlayer.Episode') or '-1'
        # in case of a special episode the video player returns none for xbmc.getInfoLabel('VideoPlayer.Season'), line 315 therefore passes season as -1.
        # episodes that are seasons start with S, i.e S1.
        # we must check then is season is -1 and episode starts with S as if True this would indicate a special episode.
        if season == -1 and episode.startswith('S'):
            # convert season from -1 to 0 as 0 tells trakt of a special season.
            season = 0
            # strip the leading S out so the episode can become an int.
            episode = episode.lstrip('S')
        # convert episode to int here as line 317 fails on conversion due to the leading S for a special episode.
        episode = int(episode)
```

I understand the code above is hacky, its not intended for use, its just there to show you what the issue is and where its happening so I hope its helpful.

Thanks.

**Comment by ghost** [comment]
After raising the issue at https://github.com/xbmc/xbmc/issues/17402

ronie has fixed the issue at https://github.com/xbmc/xbmc/pull/17408

Once this hits the 19 nighties and I can confirm that trakt now works with specials correctly I will close the issue.

**Comment by ghost** [comment]
xbmc/xbmc#17408 merged so this issue can be closed
