### ISSUE TITLE
Multiple exceptions from this script

### ISSUE THREAD

**Issue by rfgamaral** [razzeee/script.trakt#496]
Hi,

I only use this extension for one thing and one thing only, to get a rating popup at the end of a movie, that's how I have the script configured. But this stopped working for me some time ago and I didn't bother to come here until now.

When I start playing something, `kodi.log` will show this:

```
2020-03-15 17:24:06.296 T:25879   FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("argument of type 'NoneType' is not iterable",)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/service.py", line 41, in _dispatch
                                                self.scrobbler.playbackStarted(data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 168, in playbackStarted
                                                elif kodiUtilities.getSettingAsBool('rate_movie') and utilities.isMovie(self.curVideo['type']) and 'ids' in self.curVideoInfo:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
```

And after playing something I'm expecting the rating popup which doesn't show and `kodi.log` will show this:

```
2020-03-15 19:21:25.436 T:25879   FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("argument of type 'NoneType' is not iterable",)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/service.py", line 43, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 243, in playbackEnded
                                                ratingCheck(self.curVideo['type'], self.videosToRate, self.watchedTime, self.videoDuration)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/rating.py", line 27, in ratingCheck
                                                rateMedia(media_type, items_to_rate)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/rating.py", line 37, in rateMedia
                                                elif 'user' not in summary_info:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
```

This didn't use to happen a few months ago, I haven't changed a thing besides having auto-updates for both Kodi and all add-ons and scripts. Nore sure if relevant but I use Kodi for Emby to sync my Emby media files to Kodi.

**Comment by razzeee** [comment]
Do you use nfo files?

**Comment by rfgamaral** [comment]
> 
> 
> Do you use nfo files?

Yes.

**Comment by razzeee** [comment]
Can you recreate those with up to date versions of the tool you created them with? The id handling changed afaik.

**Comment by rfgamaral** [comment]
> 
> 
> Can you recreate those with up to date versions of the tool you created them with? The id handling changed afaik.

I believe I have everything updated and here's an NFO example:

```xml
<movie>
  <title>The Irishman</title>
  <rating>7.8</rating>
  <plot>Pennsylvania, 1956. Frank Sheeran, a war veteran of Irish origin who works as a truck driver, accidentally meets mobster Russell Bufalino. Once Frank becomes his trusted man, Bufalino sends him to Chicago with the task of helping Jimmy Hoffa, a powerful union leader related to organized crime, with whom Frank will maintain a close friendship for nearly twenty years.</plot>
  <id>tt1302006</id>
  <uniqueid type="imdb" default="true">tt1302006</uniqueid>
  <uniqueid type="tmdb">398978</uniqueid>
  <year>2019</year>
  <premiered>2019-11-01</premiered>
  <studio>Tribeca Productions</studio>
  <thumb />
  <thumb aspect="poster">http://image.tmdb.org/t/p/original/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg</thumb>
  <fanart>
    <thumb>http://image.tmdb.org/t/p/original/nAlOfW2FXchBljZchzjWQWgypVq.jpg</thumb>
  </fanart>
  <watched>false</watched>
  <fileinfo>
    <streamdetails>
      <video>
        <aspect>1.849711</aspect>
        <bitrate>11610094</bitrate>
        <codec>x265</codec>
        <framerate>24.000</framerate>
        <height>2076</height>
        <scantype></scantype>
        <width>3840</width>
        <duration>209.44266666666667</duration>
        <durationinseconds>12566.56</durationinseconds>
      </video>
      <audio>
        <bitrate>768000</bitrate>
        <channels>6</channels>
        <codec>EAC3</codec>
        <language>English</language>
      </audio>
      <subtitle>
        <language>English</language>
      </subtitle>
    </streamdetails>
  </fileinfo>
</movie>
```

Just so I understand, what's wrong with the above NFO and what would the fixed version look like?

**Comment by razzeee** [comment]
As long as you have you ids in a `uniqueid` field, you should be fine.

**Comment by rfgamaral** [comment]
Well, I just did a test run with the movie above and I still go these:

**After playback started:**

```
2020-03-17 11:35:23.952 T:16418   FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("argument of type 'NoneType' is not iterable",)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/service.py", line 41, in _dispatch
                                                self.scrobbler.playbackStarted(data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 168, in playbackStarted
                                                elif kodiUtilities.getSettingAsBool('rate_movie') and utilities.isMovie(self.curVideo['type']) and 'ids' in self.curVideoInfo:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
```

**After playback ended:**

```
2020-03-17 11:35:51.076 T:16418   FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("argument of type 'NoneType' is not iterable",)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/service.py", line 43, in _dispatch
                                                self.scrobbler.playbackEnded()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 243, in playbackEnded
                                                ratingCheck(self.curVideo['type'], self.videosToRate, self.watchedTime, self.videoDuration)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/rating.py", line 27, in ratingCheck
                                                rateMedia(media_type, items_to_rate)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/rating.py", line 37, in rateMedia
                                                elif 'user' not in summary_info:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
```

And I still got no rating popup...

**Comment by razzeee** [comment]
Are you able to log out `self.curVideo` and `self.curVideoInfo` before line 168 in scrobbler.py? Or are you strictly a user? :)

**Comment by rfgamaral** [comment]
> 
> 
> Are you able to log out `self.curVideo` and `self.curVideoInfo` before line 168 in scrobbler.py? Or are you strictly a user? :)

I can do it, it's my hardware :)

Though Python is not my thing, can you post the exact lines I should add before line 168?

**Comment by razzeee** [comment]
```py
logger.debug("curVideo: %s curVideoInfo: %s" % (self.curVideo, self.curVideoInfo))
```
in line 165 should work

**Comment by rfgamaral** [comment]
Hi @Razzeee,

Sorry for the delay, here's the requested log:

```
2020-03-26 21:42:05.825 T:9652   DEBUG: [script.trakt] resources.lib.kodiUtilities: getMovieDetailsFromKodi(): {u'moviedetails': {u'movieid': 1, u'uniqueid': {u'imdb': u'tt8106534'}, u'title': u'6 Underground', u'lastplayed': u'2020-03-26 21:41:35', u'label': u'6 Underground', u'file': u'http://127.0.0.1:57578/emby/kodi/movies/28522/file.strm?KodiId=1&Name=Redacted.Movile.File.mkv&Id=28522', u'year': 1601, u'playcount': 0}}
2020-03-26 21:42:05.825 T:9652   DEBUG: [script.trakt] resources.lib.kodiUtilities: checkExclusion(): Video is playing via HTTP source, which is currently set as excluded location.
2020-03-26 21:42:05.826 T:9652   DEBUG: [script.trakt] resources.lib.scrobbler: Movie type, curVideoInfo: None
2020-03-26 21:42:05.826 T:9652   DEBUG: [script.trakt] resources.lib.scrobbler: curVideo: {u'type': u'movie', u'id': 1} curVideoInfo: None
2020-03-26 21:42:05.827 T:9652   FATAL: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("argument of type 'NoneType' is not iterable",)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/service.py", line 41, in _dispatch
                                                self.scrobbler.playbackStarted(data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/scrobbler.py", line 170, in playbackStarted
                                                elif kodiUtilities.getSettingAsBool('rate_movie') and utilities.isMovie(self.curVideo['type']) and 'ids' in self.curVideoInfo:
                                            TypeError: argument of type 'NoneType' is not iterable
                                            -->End of Python script error report<--
```

**Comment by razzeee** [comment]
`2020-03-26 21:42:05.825 T:9652   DEBUG: [script.trakt] resources.lib.kodiUtilities: checkExclusion(): Video is playing via HTTP source, which is currently set as excluded location.`

Seems suspicious, can you remove that blacklisting?

**Comment by rfgamaral** [comment]
> Seems suspicious, can you remove that blacklisting?

All try that as soon as possible but now that I think about it, I remember having seen a setting like that somewhere and it might actually be the cause. I'm using Emby connected to Kodi and there are 2 different ways to play files, one is HTTP, the other is direct file system play. I'm using the former now but I believe I was using the latter in the past, that's probably the reason why this stopped working.

Will try to remove the HTTP sources from the blacklist and see how it goes :)

**Comment by rfgamaral** [comment]
@Razzeee Tested this yesterday and removing the "HTTP Sources" exclusion didn't solve it for me. However, I've changed how Kodi connects to my Emby server and used "Direct Paths" as opposed to "Add-on (Default)" (I guess I don't really need the features provided by the add-on mode) and now I got the rating popup after watching a movie.

The problem is solved for me, thank you for your assistance.
