### ISSUE TITLE
Trakt no longer syncing, hangs

### ISSUE THREAD

**Issue by TheOttoman2012** [razzeee/script.trakt#517]
Using Kodi 19.0-Alpha3 (18.9.730), and Trakt 3.3.2 I run into the following error on startup, after my library finishes scanning:

```
2020-11-25 11:35:26.621 T:32612   ERROR <general>: Exception in thread 
2020-11-25 11:35:26.621 T:32612   ERROR <general>: trakt-sync
2020-11-25 11:35:26.621 T:32612   ERROR <general>: :
                                                   
2020-11-25 11:35:26.621 T:32612   ERROR <general>: Traceback (most recent call last):
                                                   
2020-11-25 11:35:26.621 T:32612   ERROR <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2020-11-25 11:35:26.623 T:32612   ERROR <general>:     
2020-11-25 11:35:26.623 T:32612   ERROR <general>: self.run()
2020-11-25 11:35:26.623 T:32612   ERROR <general>: 
                                                   
2020-11-25 11:35:26.623 T:32612   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/service.py", line 379, in run
                                                   
2020-11-25 11:35:26.624 T:32612   ERROR <general>:     
2020-11-25 11:35:26.624 T:32612   ERROR <general>: sync.sync()
2020-11-25 11:35:26.624 T:32612   ERROR <general>: 
                                                   
2020-11-25 11:35:26.624 T:32612   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/sync.py", line 57, in sync
                                                   
2020-11-25 11:35:26.625 T:32612   ERROR <general>:     
2020-11-25 11:35:26.625 T:32612   ERROR <general>: syncMovies.SyncMovies(self, progress)
2020-11-25 11:35:26.625 T:32612   ERROR <general>: 
                                                   
2020-11-25 11:35:26.625 T:32612   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/syncMovies.py", line 21, in __init__
                                                   
2020-11-25 11:35:26.626 T:32612   ERROR <general>:     
2020-11-25 11:35:26.626 T:32612   ERROR <general>: kodiMovies = self.__kodiLoadMovies()
2020-11-25 11:35:26.626 T:32612   ERROR <general>: 
                                                   
2020-11-25 11:35:26.626 T:32612   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/syncMovies.py", line 74, in __kodiLoadMovies
                                                   
2020-11-25 11:35:26.626 T:32612   ERROR <general>:     
2020-11-25 11:35:26.626 T:32612   ERROR <general>: kodi_movies = kodiUtilities.kodiRpcToTraktMediaObjects(data)
2020-11-25 11:35:26.626 T:32612   ERROR <general>: 
                                                   
2020-11-25 11:35:26.626 T:32612   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/kodiUtilities.py", line 204, in kodiRpcToTraktMediaObjects
                                                   
2020-11-25 11:35:26.627 T:32612   ERROR <general>:     
2020-11-25 11:35:26.627 T:32612   ERROR <general>: movieObject = kodiRpcToTraktMediaObject('movie', movie, mode)
2020-11-25 11:35:26.627 T:32612   ERROR <general>: 
                                                   
2020-11-25 11:35:26.627 T:32612   ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/kodiUtilities.py", line 166, in kodiRpcToTraktMediaObject
                                                   
2020-11-25 11:35:26.627 T:32612   ERROR <general>:     
2020-11-25 11:35:26.627 T:32612   ERROR <general>: data['ids'] = data.pop('uniqueid')
2020-11-25 11:35:26.628 T:32612   ERROR <general>: 
                                                   
2020-11-25 11:35:26.628 T:32612   ERROR <general>: KeyError
2020-11-25 11:35:26.628 T:32612   ERROR <general>: : 
2020-11-25 11:35:26.628 T:32612   ERROR <general>: 'uniqueid'
2020-11-25 11:35:26.628 T:32612   ERROR <general>: 
```

Running the Add-on independently, I get the Synchronize Movies window, and "Loading movies from Kodi" message. It hangs at 0% and this is my log file.:

Kodi is unresponsive and I have to hard stop it.

```
2020-11-25 11:43:16.892 T:859      INFO <general>: initializing python engine.
2020-11-25 11:43:17.141 T:859   WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2020-11-25 11:43:17.153 T:859      INFO <general>: CPythonInvoker(19, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/defaultscript.py): script successfully run
2020-11-25 11:43:17.451 T:859   WARNING <general>: CPythonInvoker(19, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/defaultscript.py): the python script "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/defaultscript.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2020-11-25 11:43:17.451 T:859      INFO <general>: Python interpreter stopped
2020-11-25 11:43:18.025 T:32333    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2020-11-25 11:43:20.088 T:860     ERROR <general>: Exception in thread 
2020-11-25 11:43:20.088 T:860     ERROR <general>: trakt-sync
2020-11-25 11:43:20.088 T:860     ERROR <general>: :
                                                   
2020-11-25 11:43:20.088 T:860     ERROR <general>: Traceback (most recent call last):
                                                   
2020-11-25 11:43:20.088 T:860     ERROR <general>:   File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
                                                   
2020-11-25 11:43:20.090 T:860     ERROR <general>:     
2020-11-25 11:43:20.090 T:860     ERROR <general>: self.run()
2020-11-25 11:43:20.090 T:860     ERROR <general>: 
                                                   
2020-11-25 11:43:20.090 T:860     ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/service.py", line 379, in run
                                                   
2020-11-25 11:43:20.091 T:860     ERROR <general>:     
2020-11-25 11:43:20.091 T:860     ERROR <general>: sync.sync()
2020-11-25 11:43:20.091 T:860     ERROR <general>: 
                                                   
2020-11-25 11:43:20.091 T:860     ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/sync.py", line 57, in sync
                                                   
2020-11-25 11:43:20.092 T:860     ERROR <general>:     
2020-11-25 11:43:20.092 T:860     ERROR <general>: syncMovies.SyncMovies(self, progress)
2020-11-25 11:43:20.092 T:860     ERROR <general>: 
                                                   
2020-11-25 11:43:20.092 T:860     ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/syncMovies.py", line 21, in __init__
                                                   
2020-11-25 11:43:20.093 T:860     ERROR <general>:     
2020-11-25 11:43:20.093 T:860     ERROR <general>: kodiMovies = self.__kodiLoadMovies()
2020-11-25 11:43:20.093 T:860     ERROR <general>: 
                                                   
2020-11-25 11:43:20.093 T:860     ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/syncMovies.py", line 74, in __kodiLoadMovies
                                                   
2020-11-25 11:43:20.093 T:860     ERROR <general>:     
2020-11-25 11:43:20.093 T:860     ERROR <general>: kodi_movies = kodiUtilities.kodiRpcToTraktMediaObjects(data)
2020-11-25 11:43:20.093 T:860     ERROR <general>: 
                                                   
2020-11-25 11:43:20.093 T:860     ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/kodiUtilities.py", line 204, in kodiRpcToTraktMediaObjects
                                                   
2020-11-25 11:43:20.094 T:860     ERROR <general>:     
2020-11-25 11:43:20.094 T:860     ERROR <general>: movieObject = kodiRpcToTraktMediaObject('movie', movie, mode)
2020-11-25 11:43:20.094 T:860     ERROR <general>: 
                                                   
2020-11-25 11:43:20.094 T:860     ERROR <general>:   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/resources/lib/kodiUtilities.py", line 166, in kodiRpcToTraktMediaObject
                                                   
2020-11-25 11:43:20.094 T:860     ERROR <general>:     
2020-11-25 11:43:20.094 T:860     ERROR <general>: data['ids'] = data.pop('uniqueid')
2020-11-25 11:43:20.094 T:860     ERROR <general>: 
                                                   
2020-11-25 11:43:20.094 T:860     ERROR <general>: KeyError
2020-11-25 11:43:20.094 T:860     ERROR <general>: : 
2020-11-25 11:43:20.094 T:860     ERROR <general>: 'uniqueid'
2020-11-25 11:43:20.094 T:860     ERROR <general>: 

2020-11-25 11:43:32.473 T:32333    INFO <general>: Samba is idle. Closing the remaining connections
```

**Comment by razzeee** [comment]
Your library doensn't seem to have `uniqueid` set, if your using nfo, make sure to update all your files with your media manager of choice.

**Comment by TheOttoman2012** [comment]
So, a couple of things:             

- Different install of Kodi (build 18.7) and Trakt 3.2.5 works completely fine with the same library.
 I updated all of the files in the Movies folder with uniqueid fields like below using Ember.
```
  <uniqueid type="imdb" default="true">ttxxxxxxx</uniqueid>
  <uniqueid type="tmdb" default="false">xxxxx</uniqueid>
```

I re-ran Kodi 19.0-Alpha3 (18.9.730), and Trakt 3.3.2 and get the same error.

**Comment by razzeee** [comment]
Using the same scraper?

**Comment by TheOttoman2012** [comment]
> Using the same scraper?

Ah! I think that's the problem. The newer install was using the Universal Movie Scraper, while the older one was using the basic TheMovie DB scraper. I hadn't noticed that they were different. I mirrored them both and it's working fine now.

Thanks for the help, and apologies for this not being a trakt bug.

**Comment by razzeee** [comment]
Awesome, glad it's fixed
