### ISSUE TITLE
Add-on unusable after upgrading python to 3.10

### ISSUE THREAD

**Issue by tomyangsh** [Razzeee/script.trakt#586]
After I upgraded python to 3.10, the add-on showes error right after I start Kodi(19.3). 

The full log is at [https://fars.ee/37Xn](https://fars.ee/37Xn).

## Kodi log

```
2022-01-09 08:38:53.526 T:12163   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: Cursor() argument 1 must be sqlite3.Connection, not sqlite3.Connection
                                                   Traceback (most recent call last):
                                                     File "/home/tomyang/.kodi/addons/script.trakt/default.py", line 6, in <module>
                                                       from resources.lib.service import traktService
                                                     File "/home/tomyang/.kodi/addons/script.trakt/resources/lib/service.py", line 25, in <module>
                                                       class traktService:
                                                     File "/home/tomyang/.kodi/addons/script.trakt/resources/lib/service.py", line 29, in traktService
                                                       dispatchQueue = sqlitequeue.SqliteQueue()
                                                     File "/home/tomyang/.kodi/addons/script.trakt/resources/lib/sqlitequeue.py", line 56, in __init__
                                                       conn.execute(self._create)
                                                   TypeError: Cursor() argument 1 must be sqlite3.Connection, not sqlite3.Connection
                                                   -->End of Python script error report<--
                                                   
2022-01-09 08:38:53.527 T:12163   DEBUG <general>: onExecutionDone(6, /home/tomyang/.kodi/addons/script.trakt/default.py)
```

**Comment by akyag** [comment]
Any updates on this? Facing the same problem here.

**Comment by razzeee** [comment]
Haven't really looked at it, but python 3.10 has been really buggy and kodi is in general waiting for upstream to fix these. As for e.g. the sub-interpreter problems are a regression as far as I'm aware.

**Comment by droopified** [comment]
I noticed that when I add a single movie with an external scraper it doesn't mark it as 'collected' anymore until I manually scan the whole library in Kodi. Please fix this!

**Comment by razzeee** [comment]
That was never the case.

**Comment by akyag** [comment]
Has anyone found an alternative to this addon?

**Comment by razzeee** [comment]
You should be able to just use the flatpak instead, that should be unaffected by this.

**Comment by akyag** [comment]
That worked too but I am not much into runnning any flatpak or snap versions. Luckily the latest Python update [3.10.4-1] seems to have solved my issue and the addon is working correctly. :)

**Comment by razzeee** [comment]
@tomyangsh can you confirm?

**Comment by tomyangsh** [comment]
> @tomyangsh can you confirm?

After upgrading Python to `3.10.4-1`, the add-on doesn't crash Kodi right after I  started the program. While the crash did happen after I did a manual sync. I upload the full log [here](https://fars.ee/hb2f). Sorry I decide to no longer use this add-on, and won't do any test in the future.
