### ISSUE TITLE
Windows _naive_is_dst , known python issue.

### ISSUE THREAD

**Issue by Lunatixz** [Razzeee/script.trakt#592]
https://bugs.python.org/issue31327

```
2022-04-05 15:08:29.156 T:5576    ERROR <general>: trakt-sync
2022-04-05 15:08:29.156 T:5576    ERROR <general>: :
                                                   
2022-04-05 15:08:29.156 T:5576    ERROR <general>: Traceback (most recent call last):
                                                   
2022-04-05 15:08:29.156 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\system\python\Lib\threading.py", line 932, in _bootstrap_inner
                                                   
2022-04-05 15:08:29.156 T:5576    ERROR <general>:     
2022-04-05 15:08:29.156 T:5576    ERROR <general>: self.run()
2022-04-05 15:08:29.156 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.156 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.trakt\resources\lib\service.py", line 371, in run
                                                   
2022-04-05 15:08:29.165 T:5576    ERROR <general>:     
2022-04-05 15:08:29.165 T:5576    ERROR <general>: sync.sync()
2022-04-05 15:08:29.165 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.165 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.trakt\resources\lib\sync.py", line 57, in sync
                                                   
2022-04-05 15:08:29.177 T:5576    ERROR <general>:     
2022-04-05 15:08:29.177 T:5576    ERROR <general>: syncMovies.SyncMovies(self, progress)
2022-04-05 15:08:29.177 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.177 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.trakt\resources\lib\syncMovies.py", line 21, in __init__
                                                   
2022-04-05 15:08:29.191 T:5576    ERROR <general>:     
2022-04-05 15:08:29.191 T:5576    ERROR <general>: kodiMovies = self.__kodiLoadMovies()
2022-04-05 15:08:29.191 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.191 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.trakt\resources\lib\syncMovies.py", line 74, in __kodiLoadMovies
                                                   
2022-04-05 15:08:29.192 T:5576    ERROR <general>:     
2022-04-05 15:08:29.192 T:5576    ERROR <general>: kodi_movies = kodiUtilities.kodiRpcToTraktMediaObjects(data)
2022-04-05 15:08:29.192 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.192 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.trakt\resources\lib\kodiUtilities.py", line 245, in kodiRpcToTraktMediaObjects
                                                   
2022-04-05 15:08:29.202 T:5576    ERROR <general>:     
2022-04-05 15:08:29.203 T:5576    ERROR <general>: movieObject = kodiRpcToTraktMediaObject('movie', movie, mode)
2022-04-05 15:08:29.203 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.203 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.trakt\resources\lib\kodiUtilities.py", line 187, in kodiRpcToTraktMediaObject
                                                   
2022-04-05 15:08:29.203 T:5576    ERROR <general>:     
2022-04-05 15:08:29.203 T:5576    ERROR <general>: data['watched_at'] = utilities.convertDateTimeToUTC(
2022-04-05 15:08:29.203 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.203 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.trakt\resources\lib\utilities.py", line 194, in convertDateTimeToUTC
                                                   
2022-04-05 15:08:29.209 T:5576    ERROR <general>:     
2022-04-05 15:08:29.209 T:5576    ERROR <general>: utc = local.astimezone(tzutc())
2022-04-05 15:08:29.209 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.209 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 222, in utcoffset
                                                   
2022-04-05 15:08:29.211 T:5576    ERROR <general>:     
2022-04-05 15:08:29.211 T:5576    ERROR <general>: if self._isdst(dt):
2022-04-05 15:08:29.211 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.211 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 291, in _isdst
                                                   
2022-04-05 15:08:29.213 T:5576    ERROR <general>:     
2022-04-05 15:08:29.213 T:5576    ERROR <general>: dstval = self._naive_is_dst(dt)
2022-04-05 15:08:29.213 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.213 T:5576    ERROR <general>:   File "C:\Program Files\Kodi\portable_data\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 260, in _naive_is_dst
                                                   
2022-04-05 15:08:29.214 T:5576    ERROR <general>:     
2022-04-05 15:08:29.214 T:5576    ERROR <general>: return time.localtime(timestamp + time.timezone).tm_isdst
2022-04-05 15:08:29.214 T:5576    ERROR <general>: 
                                                   
2022-04-05 15:08:29.214 T:5576    ERROR <general>: OSError
2022-04-05 15:08:29.214 T:5576    ERROR <general>: : 
2022-04-05 15:08:29.214 T:5576    ERROR <general>: [Errno 22] Invalid argument
2022-04-05 15:08:29.215 T:5576    ERROR <general>: 
```

**Comment by razzeee** [comment]
https://github.com/dateutil/dateutil/issues/434
