### ISSUE TITLE
Sync stuck at "Trakt episode playcounts are up to date"

### ISSUE THREAD

**Issue by tomeczeka** [Razzeee/script.trakt#630]
I recently started using Kodi with Trakt and so far had no issues. Today though, forcing sync by running the add-on started freezing the whole app at "Trakt episode playcounts are up to date". Films sync successfully before it gets stuck.

I have two different sources for shows, two local drives. I figured the sync worked well for the first drive and it broke when some time after introducing the second one. I therefore deleted my entire "shows" library and started adding shows manually a couple at the time trying to sync after each batch.

The sync worked fine for the first 6 batches of 5 shows, correctly downloading my progress. But then, at the last batch it broke again. I decided to double-check, deleted the shows from the last batch to bring it to the last point it worked; hoping this would fix the syncing issue -- it didn't. It's permanently broken again.

I deleted the entirety of drive two, the sync started working again.

I decided to try it the other way and start with the last batch which seemed to break stuff. I added the shows one at the time and tried syncing after each one: White Lotos, TWIN, Tehran. The sync worked after adding each one of them, but broke when introducing entire library (32 shows) so I'm all out of ideas what could be wrong.

I use Kodi 20.2 on Windows 10 and my library is based on themoviedb just like Trakt.

also this seems to be the same issue as [this forum post](https://forum.kodi.tv/showthread.php?tid=374659), but I didn't find any github mention of this.

**Comment by tomeczeka** [comment]
below is the log excerpt with the errors
```
2023-12-18 21:48:34.685 T:11644   error <general>: Exception in thread 
2023-12-18 21:48:34.685 T:11644   error <general>: trakt-sync
2023-12-18 21:48:34.685 T:11644   error <general>: :
                                                   
2023-12-18 21:48:34.685 T:11644   error <general>: Traceback (most recent call last):
                                                   
2023-12-18 21:48:34.685 T:11644   error <general>:   File "C:\Program Files\Kodi\system\python\Lib\threading.py", line 932, in _bootstrap_inner
                                                   
2023-12-18 21:48:34.686 T:11644   error <general>:     
2023-12-18 21:48:34.686 T:11644   error <general>: self.run()
2023-12-18 21:48:34.686 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.686 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\service.py", line 371, in run
                                                   
2023-12-18 21:48:34.686 T:11644   error <general>:     
2023-12-18 21:48:34.686 T:11644   error <general>: sync.sync()
2023-12-18 21:48:34.686 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.686 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\sync.py", line 67, in sync
                                                   
2023-12-18 21:48:34.686 T:11644   error <general>:     
2023-12-18 21:48:34.686 T:11644   error <general>: syncEpisodes.SyncEpisodes(self, progress)
2023-12-18 21:48:34.686 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.686 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\syncEpisodes.py", line 60, in __init__
                                                   
2023-12-18 21:48:34.686 T:11644   error <general>:     
2023-12-18 21:48:34.686 T:11644   error <general>: self.__addEpisodesToKodiWatched(
2023-12-18 21:48:34.687 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.687 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\syncEpisodes.py", line 449, in __addEpisodesToKodiWatched
                                                   
2023-12-18 21:48:34.687 T:11644   error <general>:     
2023-12-18 21:48:34.687 T:11644   error <general>: "lastplayed": utilities.convertUtcToDateTime(episode['last_watched_at'])})
2023-12-18 21:48:34.687 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.687 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.trakt\resources\lib\utilities.py", line 210, in convertUtcToDateTime
                                                   
2023-12-18 21:48:34.687 T:11644   error <general>:     
2023-12-18 21:48:34.687 T:11644   error <general>: local = utc.astimezone(tzlocal())
2023-12-18 21:48:34.687 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.687 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\_common.py", line 144, in fromutc
                                                   
2023-12-18 21:48:34.687 T:11644   error <general>:     
2023-12-18 21:48:34.687 T:11644   error <general>: return f(self, dt)
2023-12-18 21:48:34.687 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.687 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\_common.py", line 258, in fromutc
                                                   
2023-12-18 21:48:34.688 T:11644   error <general>:     
2023-12-18 21:48:34.688 T:11644   error <general>: dt_wall = self._fromutc(dt)
2023-12-18 21:48:34.688 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.688 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\_common.py", line 222, in _fromutc
                                                   
2023-12-18 21:48:34.688 T:11644   error <general>:     
2023-12-18 21:48:34.688 T:11644   error <general>: dtoff = dt.utcoffset()
2023-12-18 21:48:34.688 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.688 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 222, in utcoffset
                                                   
2023-12-18 21:48:34.688 T:11644   error <general>:     
2023-12-18 21:48:34.688 T:11644   error <general>: if self._isdst(dt):
2023-12-18 21:48:34.688 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.689 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 291, in _isdst
                                                   
2023-12-18 21:48:34.689 T:11644   error <general>:     
2023-12-18 21:48:34.689 T:11644   error <general>: dstval = self._naive_is_dst(dt)
2023-12-18 21:48:34.689 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.689 T:11644   error <general>:   File "C:\Users\tomas\AppData\Roaming\Kodi\addons\script.module.dateutil\lib\dateutil\tz\tz.py", line 260, in _naive_is_dst
                                                   
2023-12-18 21:48:34.689 T:11644   error <general>:     
2023-12-18 21:48:34.689 T:11644   error <general>: return time.localtime(timestamp + time.timezone).tm_isdst
2023-12-18 21:48:34.689 T:11644   error <general>: 
                                                   
2023-12-18 21:48:34.689 T:11644   error <general>: OSError
2023-12-18 21:48:34.689 T:11644   error <general>: : 
2023-12-18 21:48:34.689 T:11644   error <general>: [Errno 22] Invalid argument
2023-12-18 21:48:34.689 T:11644   error <general>: 
```

**Comment by razzeee** [comment]
Yeah, that's a windows bug that's trackend in https://github.com/trakt/script.trakt/issues/592

**Comment by tomeczeka** [comment]
Yeah, this confirms this issue is with how Windows handles timezones. Changing timezone in Windows system settings temporarily fixes the error, but I also tried upgrading python _dateutil_ which handles UTC conversion just like someone suggested `pip install python-dateutil` and it seems to be fully fixed for now. Though suddenly ratings stopped updating? How could this even be related?

edit: no it isn't. again, worked temporarily

**Comment by tomeczeka** [comment]
It seems force-updating dateutil inside Kodi data files fixes the issue permanently:

1. download [dateutil 2.8.2](https://pypi.org/project/python-dateutil/#files) and unpack
2. backup `dateutil` folder in `\AppData\Roaming\Kodi\addons\script.module.dateutil\lib`
3. replace it with the `dateutil` from the downloaded archive
4. enable scrobbling for tv and films and Debug mode in Trakt for Kodi settings

Did this yesterday and it still works flawlessly

**Comment by razzeee** [comment]
That's weird, kodi is shipping that exact same version https://github.com/razzeee/script.module.dateutil

**Comment by tomeczeka** [comment]
Yeah, clearly. But for whatever reason this immediately solved all the issues I had

**Comment by razzeee** [comment]
You don't happen to still have the old files and could do a diff?

**Comment by tomeczeka** [comment]
I do, but to be frank I am not sure how to compare two directories

**Comment by razzeee** [comment]
If you are familiar with git, it would be pretty easy. Otherwise there may are some tools online, that allow to do this, anyway don't feel pressured to go through with this.

**Comment by tomeczeka** [comment]
> If you are familiar with git, it would be pretty easy. Otherwise there may are some tools online, that allow to do this, anyway don't feel pressured to go through with this.

I will figure it out at some point. But the solution I posted seems to still work
