### ISSUE TITLE
Some errors occurred when syncing the playback progress

### ISSUE THREAD

**Issue by luanche** [Razzeee/script.trakt#646]
## Expected Behavior

sync the movies or tv shows playback progress normally.

## Current Behavior

some errors in log when I tried to syncing playback progress back to Kodi

## Possible Solution

I have no idea, but I will post my log on https://paste.kodi.tv/utixeqaces
```
2024-05-11 19:20:39.263 T:13041   error <general>: Exception in thread 
2024-05-11 19:20:39.263 T:13041   error <general>: trakt-sync
2024-05-11 19:20:39.263 T:13041   error <general>: :
                                                   
2024-05-11 19:20:39.263 T:13041   error <general>: 
2024-05-11 19:20:39.263 T:13041   error <general>: Traceback (most recent call last):
                                                   
2024-05-11 19:20:39.263 T:13041   error <general>: 
2024-05-11 19:20:39.263 T:13041   error <general>:   File "/Applications/Kodi.app/Contents/Libraries/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
                                                   
2024-05-11 19:20:39.264 T:13041   error <general>: 
2024-05-11 19:20:39.264 T:13041   error <general>:     
2024-05-11 19:20:39.264 T:13041   error <general>: self.run()
2024-05-11 19:20:39.264 T:13041   error <general>: 
                                                   
2024-05-11 19:20:39.264 T:13041   error <general>: 
2024-05-11 19:20:39.264 T:13041   error <general>:   File "/Users/luanche/Library/Application Support/Kodi/addons/script.trakt/resources/lib/service.py", line 424, in run
                                                   
2024-05-11 19:20:39.265 T:13041   error <general>: 
2024-05-11 19:20:39.265 T:13041   error <general>:     
2024-05-11 19:20:39.265 T:13041   error <general>: sync.sync()
2024-05-11 19:20:39.265 T:13041   error <general>: 
                                                   
2024-05-11 19:20:39.265 T:13041   error <general>: 
2024-05-11 19:20:39.265 T:13041   error <general>:   File "/Users/luanche/Library/Application Support/Kodi/addons/script.trakt/resources/lib/sync.py", line 60, in sync
                                                   
2024-05-11 19:20:39.265 T:13041   error <general>: 
2024-05-11 19:20:39.265 T:13041   error <general>:     
2024-05-11 19:20:39.265 T:13041   error <general>: syncMovies.SyncMovies(self, progress)
2024-05-11 19:20:39.265 T:13041   error <general>: 
                                                   
2024-05-11 19:20:39.266 T:13041   error <general>: 
2024-05-11 19:20:39.266 T:13041   error <general>:   File "/Users/luanche/Library/Application Support/Kodi/addons/script.trakt/resources/lib/syncMovies.py", line 53, in __init__
                                                   
2024-05-11 19:20:39.266 T:13041   error <general>: 
2024-05-11 19:20:39.266 T:13041   error <general>:     
2024-05-11 19:20:39.266 T:13041   error <general>: self.__addMovieProgressToKodi(traktMoviesProgress, kodiMovies, 81, 91)
2024-05-11 19:20:39.266 T:13041   error <general>: 
                                                   
2024-05-11 19:20:39.266 T:13041   error <general>: 
2024-05-11 19:20:39.266 T:13041   error <general>:   File "/Users/luanche/Library/Application Support/Kodi/addons/script.trakt/resources/lib/syncMovies.py", line 503, in __addMovieProgressToKodi
                                                   
2024-05-11 19:20:39.267 T:13041   error <general>: 
2024-05-11 19:20:39.267 T:13041   error <general>:     
2024-05-11 19:20:39.267 T:13041   error <general>: line2=kodiUtilities.getString(32127)
2024-05-11 19:20:39.267 T:13041   error <general>: 
                                                   
2024-05-11 19:20:39.267 T:13041   error <general>: 
2024-05-11 19:20:39.267 T:13041   error <general>:  
2024-05-11 19:20:39.267 T:13041    info <general>: Skipped 9 duplicate messages..
2024-05-11 19:20:39.267 T:13041   error <general>: ^
2024-05-11 19:20:39.268 T:13041    info <general>: Skipped 29 duplicate messages..
2024-05-11 19:20:39.268 T:13041   error <general>: 
                                                   
2024-05-11 19:20:39.268 T:13041   error <general>: 
2024-05-11 19:20:39.269 T:13041   error <general>: TypeError
2024-05-11 19:20:39.269 T:13041   error <general>: : 
2024-05-11 19:20:39.269 T:13041   error <general>: not all arguments converted during string formatting
```

## Steps to Reproduce (for bugs)

1. run Trakt in addon
2. the sync progress will stuck on syncing playback progress

## Your Environment

* Version used: script.trakt v3.6.1
* Kodi version used: Kodi (21.0 (21.0.0) Git:20240406-60c4500054) x64
* Operating System and version: Apple Inc. Macmini6,2 with macOS 10.15.7 (Version 10.15.7 (Build 19H2026))

**Comment by razzeee** [comment]
Which ui language are you using and can you provide a complete log, like mentioned in the readme (and I think in the issue template too)

**Comment by luanche** [comment]
> Which ui language are you using and can you provide a complete log, like mentioned in the readme (and I think in the issue template too)

Thanks for you reply.
You might try these configs to reproduce this issue:
1. Interface->Skin->Font:  'Arial based', 
2. Interface->Regional-Language: 'Chinese (Simple)'

**Tips: Please change the font first, then change the language or you will get an incorrect interface**

After these configs and trying to run Trakt addon manully, the sync progress will stuck on syncing playback progress.

Here is the full log file https://paste.kodi.tv/libujezefu

**Comment by razzeee** [comment]
This translation is missing a placeholder then https://github.com/trakt/script.trakt/blob/bb8e17cfc960232359a45edece17974e01171774/resources/language/resource.language.zh_CN/strings.po#L515

You can change them here https://kodi.weblate.cloud/projects/kodi-add-ons-scripts/script-trakt/zh_cn/

**Comment by luanche** [comment]
Yes, I just found it.
But I dont have access to change it. and I already sent a [suggestion](https://kodi.weblate.cloud/translate/kodi-add-ons-scripts/script-trakt/zh_cn/?checksum=5ce97f7283cab4ff&q=has%3Asuggestion#suggestions)
![image](https://github.com/trakt/script.trakt/assets/39197025/e153a3b7-6ce9-4051-9b65-f80e9e00808a)

**Comment by luanche** [comment]
Hello, I just wondering when the translation will be synced back to github. This error is literally blocking the feature.
