### ISSUE TITLE
Error when plugin starts on OpenElec

### ISSUE THREAD

**Issue by estemendoza** [Razzeee/script.trakt#70]
Hi!
Thanks so much for keeping this plugin alive.

Sadly, I can't make it work in my OpenELEC distro and this is the log:
```
21:48:21 T:140117924484864  NOTICE: [trakt] Loading 'script.trakt' version '3.0.0'
21:48:21 T:140117924484864  NOTICE: [trakt] Service thread starting.
21:48:21 T:140117882521344  NOTICE: ## OpenELEC Addon ## 0.5.7
21:48:21 T:140117924484864  NOTICE: [trakt] [traktPlayer] Initalized.
21:48:21 T:140117924484864  NOTICE: [trakt] [traktMonitor] Initalized.
21:48:21 T:140117924484864  NOTICE: [trakt] [traktAPI] Initializing.
21:48:22 T:140117890914048  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting background proc (6.0.13)
21:48:22 T:140117159159552  NOTICE: -->Python Interpreter Initialized<--
21:48:22 T:140117335340800  NOTICE:  StorageServer Module loaded RUN
21:48:22 T:140117924484864   ERROR: INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.trakt.tv
21:48:22 T:140117924484864  NOTICE: .
21:48:23 T:140117924484864   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.trakt/default.py", line 13, in <module>
                                                traktService().run()
                                              File "/storage/.kodi/addons/script.trakt/service.py", line 101, in run
                                                globals.traktapi = traktAPI()
                                              File "/storage/.kodi/addons/script.trakt/traktapi.py", line 67, in __init__
                                                self.getToken()
                                              File "/storage/.kodi/addons/script.trakt/traktapi.py", line 85, in getToken
                                                self.__token = Trakt['auth'].login(getSetting('username'), getSetting('password'))
                                              File "/storage/.kodi/addons/script.trakt/trakt/interfaces/auth.py", line 10, in login
                                                'password': password
                                              File "/storage/.kodi/addons/script.trakt/trakt/core/http.py", line 80, in post
                                                return self.request('POST', path, params, data, **kwargs)
                                              File "/storage/.kodi/addons/script.trakt/trakt/core/http.py", line 57, in request
                                                response = self.session.send(prepared)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 569, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 407, in send
                                                raise ConnectionError(err, request=request)
                                            ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
                                            -->End of Python script error report<--
```

I have all the dependencies installed and my user and password are correct, double check them.
Any ideas on what this could be?

Thanks

**Comment by Razzeee** [comment]
Are you sure the machine has connection to the internet?

**Comment by estemendoza** [comment]
Yeah, it as connection to the internet. I also tried to do a soft reset and install all over again but the problem persists.

I have another plugin that uses thetvdb.com site and this is the log:
```
10:25:32 T:140706978965248   ERROR: script.tv.show.next.aired: ### ERROR retreiving updates from thetvdb.com: [Errno socket error] [Errno -2] Name or service not known
10:25:33 T:140706978965248  NOTICE: script.tv.show.next.aired: ### data update finished
10:30:47 T:140706978965248  NOTICE: script.tv.show.next.aired: ### starting data update
10:30:47 T:140706978965248  NOTICE: script.tv.show.next.aired: ### grabbing a new country mapping list
10:30:47 T:140706978965248   ERROR: script.tv.show.next.aired: ### ERROR retreiving updates from thetvdb.com: [Errno socket error] [Errno -2] Name or service not known
10:30:48 T:140706978965248  NOTICE: script.tv.show.next.aired: ### data update finished
OpenELEC:~ # 
OpenELEC:~ # ping thetvdb.com
PING thetvdb.com (190.93.241.81): 56 data bytes
64 bytes from 190.93.241.81: seq=0 ttl=50 time=135.188 ms
64 bytes from 190.93.241.81: seq=1 ttl=50 time=134.944 ms
64 bytes from 190.93.241.81: seq=2 ttl=50 time=134.507 ms
64 bytes from 190.93.241.81: seq=3 ttl=50 time=134.169 ms
```

So that makes me wonder that it might not be a problem of the trakt plugin

**Comment by estemendoza** [comment]
Also, I tried to re-launch the plugin from the config and pressing "Launch" button does nothing

**Comment by Razzeee** [comment]
@estemendoza 
how did you install via zip?

**Comment by estemendoza** [comment]
yeah, I downloaded the zip file from here, the master zip and install it from there

**Comment by blinkseb** [comment]
I had the same error with openelec. It was because Kodi was launched before my wifi was connected. I checked the option "wait for network connection" in the OpenElec plugin and problem solved.

**Comment by estemendoza** [comment]
@blinkseb good point, I was thinking it could be something like that, but I didn't know that option on OpenELEC. I will try it again later.

**Comment by estemendoza** [comment]
Ok, got it working, I enabled that option on the OpenElec settings and it's working fine now. Thanks!
