### ISSUE TITLE
.strm files (virtual library items) are no longer being processed properly (no scrobble, etc.)

### ISSUE THREAD

**Issue by s7eele** [Razzeee/script.trakt#90]
it appears that .strm files are no longer being processed properly, they are no longer scrobbling, im not sure wether or not it has anything to do with the problem resolved with closure of issue #17 so after verifying a few things i opened this new issue, apologies if that was a mistake

from what i can tell the last commit has caused the problem to reappear, following is an excerpt of the log, at point of failure:

>22:17:21 T:1816213208  NOTICE: [trakt] [traktPlayer] onPlayBackStarted() - {u'item': {u'type': u'unknown', u'label': u'Walking Big & Tall'}}
22:17:21 T:1816213208  NOTICE: [trakt] [traktPlayer] onPlayBackStarted() - Started playing a non-library file, checking available data.
22:17:21 T:1816213208  NOTICE: [trakt] [traktPlayer] info - showtitle: The Simpsons, Year: , Season: 26, Episode: 13
22:17:21 T:1816213208  NOTICE: [trakt] [traktPlayer] onPlayBackStarted() - Playing a non-library 'episode' - The Simpsons - S26E13 - Walking Big & Tall.
22:17:21 T:1816213208  NOTICE: [trakt] Queuing for dispatch: {'episode': 13, 'title': 'Walking Big & Tall', 'season': 26, 'action': 'started', 'type': 'episode', 'showtitle': 'The Simpsons'}
22:17:21 T:1816213208  NOTICE: [trakt] Queued dispatch: {u'episode': 13, u'title': u'Walking Big & Tall', u'season': 26, u'action': u'started', u'type': u'episode', u'showtitle': u'The Simpsons'}
22:17:21 T:1816213208  NOTICE: [trakt] Dispatch: {u'episode': 13, u'title': u'Walking Big & Tall', u'season': 26, u'action': u'started', u'type': u'episode', u'showtitle': u'The Simpsons'}
22:17:21 T:1816213208  NOTICE: [trakt] [Scrobbler] playbackStarted(data: {u'episode': 13, u'title': u'Walking Big & Tall', u'season': 26, u'type': u'episode', u'showtitle': u'The Simpsons'})
22:17:21 T:1816213208  NOTICE: [trakt] [Scrobbler] Watching: episode
22:17:22 T:1816213208  NOTICE: [trakt] EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'TypeError'>
                                            Error Contents: ("'NoneType' object does not support item assignment",)
                                            Traceback (most recent call last):
                                              File "/storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/service.py", line 38, in _dispatch
                                                self.scrobbler.playbackStarted(data)
                                              File "/storage/sdcard0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.trakt/scrobbler.py", line 145, in playbackStarted
                                                self.curVideoInfo['title'] = self.curVideo['title']
                                            TypeError: 'NoneType' object does not support item assignment
                                            -->End of Python script error report<--

i can post a link to a complete log if needed, i have already re-installed twice to ensure i was using latest commit and eliminate installation as a potential cause, next i will revert to the version before this to make sure that it restores functionality, please advise if anything else is needed

**Comment by s7eele** [comment]
reopened issue #17
